export const languagesList = [
  { code: 'en', name: 'English', nativeName: 'English', speechCode: 'en-IN', flag: '🇬🇧' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', speechCode: 'te-IN', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', speechCode: 'hi-IN', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', speechCode: 'ta-IN', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', speechCode: 'kn-IN', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', speechCode: 'ml-IN', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', speechCode: 'mr-IN', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', speechCode: 'bn-IN', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', speechCode: 'gu-IN', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', speechCode: 'pa-IN', flag: '🇮🇳' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', speechCode: 'or-IN', flag: '🇮🇳' }
];

export const translations = {
  en: {
    title: "🌾 Farmer Procurement Hub",
    tagline: "Transparent, Seamless Grain Procurement & Real-time Queue Tracking",
    register: "Register Farmer",
    login: "Login with Mobile",
    sendOtp: "Send OTP",
    sendingOtp: "Sending OTP...",
    verifyOtp: "Verify OTP & Login",
    verifyingOtp: "Verifying...",
    enterOtp: "Enter 6-digit OTP",
    resendOtp: "Resend OTP",
    otpSentTo: "OTP sent to",
    demoOtpBadge: "Demo OTP for Testing:",
    bookSlot: "Book Slot",
    queueStatus: "Queue Status",
    payment: "Payment & MSP",
    logout: "Logout",
    fullName: "Full Name",
    phone: "Mobile Number",
    aadhar: "Aadhar / ID Number",
    address: "Village / District Address",
    bankAccount: "Bank Account Number",
    upi: "UPI ID (Optional)",
    registerBtn: "Register & Get Started",
    welcome: "Welcome back",
    selectSlot: "Select a Procurement Slot",
    queuePosition: "Your Queue Token",
    payNow: "Claim / Confirm Payment",
    help: "Krishi AI Assistant",
    alreadyRegistered: "Already registered? Login with Mobile Number",
    newFarmer: "New farmer? Register here",
    otpVerification: "Mobile OTP Verification",
    enterMobile: "Enter 10-digit Mobile Number",
    phoneRequired: "Please enter a valid 10-digit mobile number",
    fillAllFields: "Please fill all required fields",
    chatbotTitle: "🌾 Krishi Sahayak (Procurement AI)",
    chatPlaceholder: "Ask about centers, slots, queue tokens, payments, MSP...",
    voiceListening: "Listening... Speak now",
    voiceNotSupported: "Voice recognition is not supported in this browser",
    center: "Procurement Center",
    date: "Date",
    time: "Time Slot",
    capacity: "Capacity",
    status: "Status",
    confirmed: "Confirmed",
    pending: "Pending",
    completed: "Completed",
    totalInQueue: "Total Farmers in Queue",
    estimatedWait: "Estimated Wait Time",
    amount: "Procurement Amount (₹)",
    transactionId: "Transaction ID",
    paid: "Paid to Bank (DBT Completed)",
    unpaid: "Awaiting Admin Sanction",
    adminPanel: "Admin Panel",
    createSlot: "Create New Procurement Slot",
    allSlots: "All Scheduled Slots",
    noSlots: "No slots available at the moment.",
    noBookings: "No bookings found yet. Book your first slot above!",
    bookedSuccessfully: "Slot booked successfully!",
    loginSuccess: "Logged in successfully!",
    regSuccess: "Registered successfully! Welcome to the hub.",
    liveQueueUpdates: "Live Real-Time Queue Updates Connected",
    // Illiterate Voice Prompts
    listenVoice: "Listen Audio",
    speakMobilePrompt: "Please enter your 10 digit mobile number.",
    speakOtpPrompt: "Please enter the 6 digit OTP received on your mobile phone.",
    speakNamePrompt: "Please enter your full name as in your bank passbook.",
    speakAadharPrompt: "Please enter your 12 digit Aadhaar number.",
    speakAddressPrompt: "Please enter your village, mandal, and district address.",
    speakBankPrompt: "Please enter your bank account number for direct MSP money transfer.",
    speakUpiPrompt: "You can enter your UPI ID if you have one.",
    // Non-smartphone IVR telephone booking
    ivrTollFree: "📞 Dial-in IVR Slot Booking (No Smartphone Required)",
    ivrSubtitle: "Farmers without a smartphone can book procurement slots by dialing our toll-free number 1800-890-2026",
    dialNow: "Dial IVR Number (1800-890-2026)",
    // Strict Guardrail Notice
    strictUnrelatedNotice: "This question is not related to crop procurement. Please ask only queries regarding procurement centers, slot booking, live queue tokens, MSP rates, and farmer payments."
  },
  te: {
    title: "🌾 రైతు ధాన్య సేకరణ కేంద్రం",
    tagline: "పారదర్శక ధాన్య కొనుగోళ్లు మరియు ప్రత్యక్ష క్యూ సమాచారం",
    register: "రైతు నమోదు",
    login: "మొబైల్ నంబర్ లాగిన్",
    sendOtp: "OTP పంపండి",
    sendingOtp: "OTP పంపుతోంది...",
    verifyOtp: "OTP ధృవీకరించి లాగిన్ అవ్వండి",
    verifyingOtp: "ధృవీకరిస్తోంది...",
    enterOtp: "6 అంకెల OTP నమోదు చేయండి",
    resendOtp: "OTP మళ్లీ పంపండి",
    otpSentTo: "OTP పంపబడిన నంబర్:",
    demoOtpBadge: "పరీక్ష OTP:",
    bookSlot: "స్లాట్ బుక్ చేయండి",
    queueStatus: "క్యూ స్థితి",
    payment: "చెల్లింపు & మద్దతు ధర",
    logout: "లాగ్ అవుట్",
    fullName: "పూర్తి పేరు",
    phone: "మొబైల్ నంబర్",
    aadhar: "ఆధార్ / ID సంఖ్య",
    address: "గ్రామం / జిల్లా చిరునామా",
    bankAccount: "బ్యాంక్ ఖాతా సంఖ్య",
    upi: "UPI ID (ఐచ్ఛికం)",
    registerBtn: "నమోదు చేసి ప్రారంభించండి",
    welcome: "స్వాగతం",
    selectSlot: "సేకరణ స్లాట్ ఎంచుకోండి",
    queuePosition: "మీ క్యూ టోకెన్",
    payNow: "చెల్లింపు స్వీకరించండి",
    help: "కృషి సహాయక్ (AI)",
    alreadyRegistered: "ఇప్పటికే నమోదు చేసుకున్నారా? ఇక్కడ లాగిన్ అవ్వండి",
    newFarmer: "కొత్త రైతు? ఇక్కడ నమోదు చేసుకోండి",
    otpVerification: "మొబైల్ OTP ధృవీకరణ",
    enterMobile: "10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి",
    phoneRequired: "దయచేసి సరైన 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి",
    fillAllFields: "దయచేసి అవసరమైన అన్ని వివరాలను పూరించండి",
    chatbotTitle: "🌾 కృషి సహాయక్ (ధాన్య సేకరణ AI)",
    chatPlaceholder: "కేంద్రాలు, స్లాట్, క్యూ, చెల్లింపు లేదా మద్దతు ధర గురించి అడగండి...",
    voiceListening: "వింటున్నాను... మాట్లాడండి",
    voiceNotSupported: "ఈ బ్రౌజర్‌లో వాయిస్ రికగ్నిషన్ అందుబాటులో లేదు",
    center: "సేకరణ కేంద్రం",
    date: "తేదీ",
    time: "సమయం స్లాట్",
    capacity: "సామర్థ్యం",
    status: "స్థితి",
    confirmed: "ధృవీకరించబడింది",
    pending: "పెండింగ్‌లో ఉంది",
    completed: "పూర్తయింది",
    totalInQueue: "క్యూలో ఉన్న రైతుల సంఖ్య",
    estimatedWait: "వేచి ఉండే సమయం",
    amount: "చెల్లింపు మొత్తం (₹)",
    transactionId: "లావాదేవీ ID",
    paid: "బ్యాంకుకు జమ అయింది (DBT పూర్తయింది)",
    unpaid: "అడ్మిన్ మంజూరు కోసం వేచి ఉంది",
    adminPanel: "అడ్మిన్ ప్యానెల్",
    createSlot: "కొత్త సేకరణ స్లాట్ జోడించండి",
    allSlots: "అందుబాటులో ఉన్న స్లాట్లు",
    noSlots: "ప్రస్తుతం స్లాట్‌లు అందుబాటులో లేవు.",
    noBookings: "ఇంకా ఎటువంటి స్లాట్ బుకింగ్ లేదు.",
    bookedSuccessfully: "స్లాట్ విజయవంతంగా బుక్ చేయబడింది!",
    loginSuccess: "లాగిన్ విజయవంతమైంది!",
    regSuccess: "నమోదు పూర్తయింది! రైతు హబ్‌కు స్వాగతం.",
    liveQueueUpdates: "లైవ్ క్యూ అప్‌డేట్‌లు అందుబాటులో ఉన్నాయి",
    // Illiterate Voice Prompts
    listenVoice: "వాయిస్ వినండి",
    speakMobilePrompt: "దయచేసి మీ 10 అంకెల మొబైల్ నంబర్‌ను ఇక్కడ నమోదు చేయండి.",
    speakOtpPrompt: "మీ మొబైల్‌కు వచ్చిన 6 అంకెల ఓటీపీని ఇక్కడ నమోదు చేయండి.",
    speakNamePrompt: "దయచేసి మీ బ్యాంక్ పాస్‌బుక్‌లో ఉన్నట్లు పూర్తి పేరు నమోదు చేయండి.",
    speakAadharPrompt: "దయచేసి మీ 12 అంకెల ఆధార్ నంబర్‌ను నమోదు చేయండి.",
    speakAddressPrompt: "దయచేసి మీ గ్రామం, మండలం మరియు జిల్లా చిరునామా నమోదు చేయండి.",
    speakBankPrompt: "నేరుగా బ్యాంకు ఖాతాలో డబ్బులు జమ కావడానికి మీ బ్యాంక్ అకౌంట్ నంబర్ నమోదు చేయండి.",
    speakUpiPrompt: "మీకు యూపీఐ ఉంటే ఇక్కడ నమోదు చేయవచ్చు.",
    // Non-smartphone IVR telephone booking
    ivrTollFree: "📞 ఫోన్ కాల్ ద్వారా స్లాట్ బుకింగ్ (స్మార్ట్‌ఫోన్ లేని రైతుల కోసం)",
    ivrSubtitle: "స్మార్ట్‌ఫోన్ లేని రైతులు టోల్‌ఫ్రీ నంబర్ 1800-890-2026 కు ఫోన్ కాల్ చేసి సులభంగా స్లాట్ బుక్ చేసుకోవచ్చు",
    dialNow: "టోల్‌ఫ్రీ నంబర్‌కు కాల్ చేయండి (1800-890-2026)",
    // Strict Guardrail Notice
    strictUnrelatedNotice: "ఈ ప్రశ్న ధాన్య సేకరణకు సంబంధించినది కాదు. దయచేసి సేకరణ కేంద్రాలు, స్లాట్ బుకింగ్, క్యూ టోకెన్లు, మద్దతు ధర (MSP) మరియు రైతు చెల్లింపుల గురించి మాత్రమే అడగండి."
  },
  hi: {
    title: "🌾 किसान खरीद एवं टोकन हब",
    tagline: "पारदर्शी फसल खरीद और रीयल-टाइम कतार ट्रैकिंग",
    register: "किसान पंजीकरण",
    login: "मोबाइल नंबर से लॉगिन",
    sendOtp: "ओटीपी भेजें",
    sendingOtp: "ओटीपी भेजा जा रहा है...",
    verifyOtp: "ओटीपी सत्यापित करें और लॉगिन करें",
    verifyingOtp: "सत्यापन हो रहा है...",
    enterOtp: "6 अंकों का ओटीपी दर्ज करें",
    resendOtp: "ओटीपी पुनः भेजें",
    otpSentTo: "ओटीपी इस नंबर पर भेजा गया:",
    demoOtpBadge: "परीक्षण हेतु ओटीपी:",
    bookSlot: "स्लॉट बुक करें",
    queueStatus: "कतार स्थिति",
    payment: "भुगतान एवं एमएसपी",
    logout: "लॉगआउट",
    fullName: "पूरा नाम",
    phone: "मोबाइल नंबर",
    aadhar: "आधार / पहचान पत्र नंबर",
    address: "गाँव / जिला का पता",
    bankAccount: "बैंक खाता संख्या",
    upi: "यूपीआई आईडी (वैकल्पिक)",
    registerBtn: "पंजीकरण करें और आगे बढ़ें",
    welcome: "स्वागत है",
    selectSlot: "खरीद स्लॉट चुनें",
    queuePosition: "आपका टोकन नंबर",
    payNow: "भुगतान प्राप्त करें",
    help: "कृषि सहायक (AI)",
    alreadyRegistered: "पहले से पंजीकृत हैं? यहाँ लॉगिन करें",
    newFarmer: "नए किसान? यहाँ पंजीकरण करें",
    otpVerification: "मोबाइल ओटीपी सत्यापन",
    enterMobile: "10 अंकों का मोबाइल नंबर दर्ज करें",
    phoneRequired: "कृपया सही 10 अंकों का मोबाइल नंबर दर्ज करें",
    fillAllFields: "कृपया सभी आवश्यक विवरण भरें",
    chatbotTitle: "🌾 कृषि सहायक (फसल खरीद AI)",
    chatPlaceholder: "खरीद केंद्र, स्लॉट, कतार, भुगतान या एमएसपी के बारे में पूछें...",
    voiceListening: "सुन रहा हूँ... बोलिए",
    voiceNotSupported: "इस ब्राउज़र में ध्वनि पहचान समर्थित नहीं है",
    center: "खरीद केंद्र",
    date: "दिनांक",
    time: "समय स्लॉट",
    capacity: "क्षमता",
    status: "स्थिति",
    confirmed: "स्वीकृत",
    pending: "प्रतीक्षारत",
    completed: "पूर्ण",
    totalInQueue: "कतार में कुल किसान",
    estimatedWait: "अनुमानित प्रतीक्षा समय",
    amount: "खरीद राशि (₹)",
    transactionId: "लेनदेन संख्या",
    paid: "बैंक में स्थानांतरित (डीबीटी पूर्ण)",
    unpaid: "अधिकारी स्वीकृति प्रतीक्षारत",
    adminPanel: "व्यवस्थापक पैनल",
    createSlot: "नया खरीद स्लॉट जोड़ें",
    allSlots: "उपलब्ध स्लॉट",
    noSlots: "वर्तमान में कोई स्लॉट उपलब्ध नहीं है।",
    noBookings: "अभी तक कोई स्लॉट बुक नहीं किया गया है।",
    bookedSuccessfully: "स्लॉट सफलतापूर्वक बुक हो गया!",
    loginSuccess: "सफलतापूर्वक लॉगिन हो गया!",
    regSuccess: "पंजीकरण सफल! किसान हब में आपका स्वागत है।",
    liveQueueUpdates: "रीयल-टाइम कतार अपडेट चालू है",
    // Illiterate Voice Prompts
    listenVoice: "आवाज़ सुनें",
    speakMobilePrompt: "कृपया अपना 10 अंकों का मोबाइल नंबर दर्ज करें।",
    speakOtpPrompt: "कृपया अपने मोबाइल पर आया 6 अंकों का ओटीपी दर्ज करें।",
    speakNamePrompt: "कृपया अपना पूरा नाम बैंक पासबुक के अनुसार दर्ज करें।",
    speakAadharPrompt: "कृपया अपना 12 अंकों का आधार नंबर दर्ज करें।",
    speakAddressPrompt: "कृपया अपना गाँव, ब्लॉक और जिले का पता दर्ज करें।",
    speakBankPrompt: "एमएसपी राशि सीधे खाते में पाने के लिए अपना बैंक खाता संख्या दर्ज करें।",
    speakUpiPrompt: "यदि आपके पास यूपीआई आईडी है तो दर्ज करें।",
    // Non-smartphone IVR telephone booking
    ivrTollFree: "📞 फोन कॉल से स्लॉट बुकिंग (बिना स्मार्टफोन वाले किसानों के लिए)",
    ivrSubtitle: "जिन किसानों के पास स्मार्टफोन नहीं है, वे टोल-फ्री नंबर 1800-890-2026 पर कॉल करके स्लॉट बुक कर सकते हैं",
    dialNow: "टोल-फ्री नंबर पर कॉल करें (1800-890-2026)",
    // Strict Guardrail Notice
    strictUnrelatedNotice: "यह प्रश्न फसल खरीद से संबंधित नहीं है। कृपया केवल खरीद केंद्र, स्लॉट बुकिंग, कतार टोकन, एमएसपी दर और किसान भुगतान से संबंधित प्रश्न ही पूछें।"
  },
  ta: {
    title: "🌾 விவசாயி கொள்முதல் மையம்",
    tagline: "வெளிப்படையான தானிய கொள்முதல் மற்றும் நேரலை வரிசை கண்காணிப்பு",
    register: "விவசாயி பதிவு",
    login: "மொபைல் எண் மூலம் உள்நுழை",
    sendOtp: "OTP அனுப்பு",
    sendingOtp: "OTP அனுப்பப்படுகிறது...",
    verifyOtp: "OTP சரிபார்த்து உள்நுழையவும்",
    verifyingOtp: "சரிபார்க்கப்படுகிறது...",
    enterOtp: "6 இலக்க OTP ஐ உள்ளிடவும்",
    resendOtp: "OTP மீண்டும் அனுப்பு",
    otpSentTo: "OTP அனுப்பப்பட்ட எண்:",
    demoOtpBadge: "சோதனை OTP:",
    bookSlot: "இடத்தை முன்பதிவு செய்",
    queueStatus: "வரிசை நிலை",
    payment: "பணம் & MSP",
    logout: "வெளியேறு",
    fullName: "முழு பெயர்",
    phone: "மொபைல் எண்",
    aadhar: "ஆதார் / அடையாள எண்",
    address: "முகவரி",
    bankAccount: "வங்கி கணக்கு எண்",
    upi: "UPI ஐடி",
    registerBtn: "பதிவு செய்து தொடங்கு",
    welcome: "வரவேற்கிறோம்",
    selectSlot: "கொள்முதல் நேரத்தைத் தேர்ந்தெடு",
    queuePosition: "உங்கள் வரிசை டோக்கன்",
    payNow: "பணம் பெறுங்கள்",
    help: "விவசாய AI உதவியாளர்",
    alreadyRegistered: "ஏற்கனவே பதிவு செய்துள்ளீர்களா? உள்நுழையவும்",
    newFarmer: "புதிய விவசாயியா? பதிவு செய்யுங்கள்",
    otpVerification: "மொபைல் OTP சரிபார்ப்பு",
    enterMobile: "10 இலக்க மொபைல் எண்ணை உள்ளிடவும்",
    phoneRequired: "சரியான மொபைல் எண்ணை உள்ளிடவும்",
    fillAllFields: "அனைத்து விவரங்களையும் நிரப்பவும்",
    chatbotTitle: "🌾 கிருஷி சகாயக் (AI உதவியாளர்)",
    chatPlaceholder: "முன்பதிவு, வரிசை, பணம் பற்றி கேளுங்கள்...",
    voiceListening: "கேட்கிறது... பேசுங்கள்",
    voiceNotSupported: "குரல் அங்கீகாரம் இந்த உலாவியில் ஆதரிக்கப்படவில்லை",
    center: "கொள்முதல் மையம்",
    date: "தேதி",
    time: "நேரம்",
    capacity: "அளவு",
    status: "நிலை",
    confirmed: "உறுதியானது",
    pending: "நிலுவையில்",
    completed: "முடிந்தது",
    totalInQueue: "வரிசையில் உள்ள விவசாயிகள்",
    estimatedWait: "எதிர்பார்க்கப்படும் நேரம்",
    amount: "தொகை (₹)",
    transactionId: "பரிவர்த்தனை எண்",
    paid: "வங்கியில் செலுத்தப்பட்டது (DBT)",
    unpaid: "செயல்பாட்டில் உள்ளது",
    adminPanel: "நிர்வாக குழு",
    createSlot: "புதிய இடத்தை உருவாக்கு",
    allSlots: "அனைத்து இடங்கள்",
    noSlots: "இடங்கள் எதுவும் இல்லை.",
    noBookings: "முன்பதிவு எதுவும் இல்லை.",
    bookedSuccessfully: "இடம் முன்பதிவு செய்யப்பட்டது!",
    loginSuccess: "உள்நுழைவு வெற்றிகரமானது!",
    regSuccess: "பதிவு வெற்றிகரமானது!",
    liveQueueUpdates: "நேரலை வரிசை இணைப்பு செயலில் உள்ளது",
    listenVoice: "குரலைக் கேளுங்கள்",
    speakMobilePrompt: "உங்கள் 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்.",
    speakOtpPrompt: "உங்கள் மொபைலுக்கு வந்த 6 இலக்க OTP ஐ உள்ளிடவும்.",
    speakNamePrompt: "உங்கள் முழுப் பெயரை உள்ளிடவும்.",
    speakAadharPrompt: "உங்கள் 12 இலக்க ஆதார் எண்ணை உள்ளிடவும்.",
    speakAddressPrompt: "உங்கள் முகவரியை உள்ளிடவும்.",
    speakBankPrompt: "வங்கி கணக்கு எண்ணை உள்ளிடவும்.",
    speakUpiPrompt: "UPI ஐடியை உள்ளிடவும்.",
    ivrTollFree: "📞 தொலைபேசி மூலம் முன்பதிவு",
    ivrSubtitle: "ஸ்மார்ட்போன் இல்லாத விவசாயிகள் 1800-890-2026 என்ற எண்ணை அழைத்து முன்பதிவு செய்யலாம்",
    dialNow: "அழைக்கவும் (1800-890-2026)",
    strictUnrelatedNotice: "இந்த கேள்வி தானிய கொள்முதலுடன் தொடர்புடையது அல்ல. கொள்முதல் மையம், முன்பதிவு, வரிசை டோக்கன், MSP விலை மற்றும் பணம் செலுத்துதல் பற்றிய கேள்விகளை மட்டும் கேட்கவும்."
  },
  kn: {
    title: "🌾 ರೈತ ಧಾನ್ಯ ಖರೀದಿ ಕೇಂದ್ರ",
    tagline: "ಪಾರದರ್ಶಕ ಧಾನ್ಯ ಖರೀದಿ ಮತ್ತು ನೇರ ಸರದಿ ಸಾಲು ಪರಿಶೀಲನೆ",
    register: "ರೈತರ ನೋಂದಣಿ",
    login: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯೊಂದಿಗೆ ಲಾಗಿನ್",
    sendOtp: "OTP ಕಳುಹಿಸಿ",
    sendingOtp: "OTP ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...",
    verifyOtp: "OTP ದೃಢೀಕರಿಸಿ ಲಾಗಿನ್ ಮಾಡಿ",
    verifyingOtp: "ದೃಢೀಕರಿಸಲಾಗುತ್ತಿದೆ...",
    enterOtp: "6 ಅಂಕಿಯ OTP ನಮೂದಿಸಿ",
    resendOtp: "OTP ಮರುಕಳುಹಿಸಿ",
    otpSentTo: "OTP ಕಳುಹಿಸಿದ ಮೊಬೈಲ್:",
    demoOtpBadge: "ಪರೀಕ್ಷಾ OTP:",
    bookSlot: "ಸ್ಲಾಟ್ ಕಾಯ್ದಿರಿಸಿ",
    queueStatus: "ಸರದಿ ಸಾಲಿನ ಸ್ಥಿತಿ",
    payment: "ಪಾವತಿ ಮತ್ತು ಬೆಂಬಲ ಬೆಲೆ",
    logout: "ಲಾಗ್ ಔಟ್",
    fullName: "ಸಂಪೂರ್ಣ ಹೆಸರು",
    phone: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    aadhar: "ಆಧಾರ್ / ಗುರುತಿನ ಸಂಖ್ಯೆ",
    address: "ಗ್ರಾಮ / ವಿಳಾಸ",
    bankAccount: "ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ",
    upi: "UPI ಐಡಿ",
    registerBtn: "ನೋಂದಾಯಿಸಿ ಮುಂದುವರಿಯಿರಿ",
    welcome: "ಸ್ವಾಗತ",
    selectSlot: "ಖರೀದಿ ಸ್ಲಾಟ್ ಆಯ್ಕೆಮಾಡಿ",
    queuePosition: "ನಿಮ್ಮ ಸರದಿ ಟೋಕನ್",
    payNow: "ಪಾವತಿ ಪಡೆಯಿರಿ",
    help: "ಕೃಷಿ ಸಹಾಯಕ (AI)",
    alreadyRegistered: "ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ",
    newFarmer: "ಹೊಸ ರೈತರೇ? ಇಲ್ಲಿ ನೋಂದಾಯಿಸಿ",
    otpVerification: "ಮೊಬೈಲ್ OTP ಪರಿಶೀಲನೆ",
    enterMobile: "10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    phoneRequired: "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ 10 ಅಂಕಿಯ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    fillAllFields: "ದಯವಿಟ್ಟು ಎಲ್ಲಾ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ",
    chatbotTitle: "🌾 ಕೃಷಿ ಸಹಾಯಕ (AI ಧ್ವನಿ ಸಹಾಯಕ)",
    chatPlaceholder: "ಸ್ಲಾಟ್, ಸರದಿ, ಪಾವತಿ ಅಥವಾ MSP ಬಗ್ಗೆ ಕೇಳಿ...",
    voiceListening: "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ... ಮಾತನಾಡಿ",
    voiceNotSupported: "ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆ ಬೆಂಬಲಿತವಾಗಿಲ್ಲ",
    center: "ಖರೀದಿ ಕೇಂದ್ರ",
    date: "ದಿನಾಂಕ",
    time: "ಸಮಯ",
    capacity: "ಸಾಮರ್ಥ್ಯ",
    status: "ಸ್ಥಿತಿ",
    confirmed: "ದೃಢೀಕರಿಸಲಾಗಿದೆ",
    pending: "ಬಾಕಿ ಇದೆ",
    completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    totalInQueue: "ಸರದಿಯಲ್ಲಿರುವ ರೈತರು",
    estimatedWait: "ಅಂದಾಜು ಕಾಯುವ ಸಮಯ",
    amount: "ಮೊತ್ತ (₹)",
    transactionId: "ವಹಿವಾಟು ಐಡಿ",
    paid: "ಬ್ಯಾಂಕ್‌ಗೆ ಪಾವತಿಸಲಾಗಿದೆ (DBT)",
    unpaid: "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ",
    adminPanel: "ನಿರ್ವಾಹಕ ಫಲಕ",
    createSlot: "ಹೊಸ ಸ್ಲಾಟ್ ರಚಿಸಿ",
    allSlots: "ಲಭ್ಯವಿರುವ ಸ್ಲಾಟ್‌ಗಳು",
    noSlots: "ಯಾವುದೇ ಸ್ಲಾಟ್ ಲಭ್ಯವಿಲ್ಲ.",
    noBookings: "ಇನ್ನೂ ಯಾವುದೇ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಲಾಗಿಲ್ಲ.",
    bookedSuccessfully: "ಸ್ಲಾಟ್ ಯಶಸ್ವಿಯಾಗಿ ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ!",
    loginSuccess: "ಲಾಗಿನ್ ಯಶಸ್ವಿಯಾಗಿದೆ!",
    regSuccess: "ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ!",
    liveQueueUpdates: "ಲೈವ್ ಸರದಿ ಸಾಲು ನವೀಕರಣ ಸಕ್ರಿಯವಾಗಿದೆ",
    listenVoice: "ಧ್ವನಿ ಆಲಿಸಿ",
    speakMobilePrompt: "ದಯವಿಟ್ಟು ನಿಮ್ಮ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ.",
    speakOtpPrompt: "ನಿಮ್ಮ ಮೊಬೈಲ್‌ಗೆ ಬಂದ 6 ಅಂಕಿಯ OTP ನಮೂದಿಸಿ.",
    speakNamePrompt: "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ.",
    speakAadharPrompt: "ನಿಮ್ಮ 12 ಅಂಕಿಯ ಆಧಾರ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.",
    speakAddressPrompt: "ನಿಮ್ಮ ಗ್ರಾಮ ಮತ್ತು ಜಿಲ್ಲೆಯ ವಿಳಾಸ ನಮೂದಿಸಿ.",
    speakBankPrompt: "ನೇರ ಪಾವತಿಗಾಗಿ ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ.",
    speakUpiPrompt: "UPI ಐಡಿ ನಮೂದಿಸಿ.",
    ivrTollFree: "📞 ಫೋನ್ ಕರೆ ಮೂಲಕ ಸ್ಲಾಟ್ ಬುಕಿಂಗ್",
    ivrSubtitle: "ಸ್ಮಾರ್ಟ್‌ಫೋನ್ ಇಲ್ಲದ ರೈತರು 1800-890-2026 ಕರೆ ಮಾಡಿ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಬಹುದು",
    dialNow: "ಕರೆ ಮಾಡಿ (1800-890-2026)",
    strictUnrelatedNotice: "ಈ ಪ್ರಶ್ನೆಯು ಧಾನ್ಯ ಖರೀದಿಗೆ ಸಂಬಂಧಿಸಿಲ್ಲ. ದಯವಿಟ್ಟು ಖರೀದಿ ಕೇಂದ್ರ, ಸ್ಲಾಟ್ ಬುಕಿಂಗ್, ಸರದಿ ಟೋಕನ್, ಬೆಂಬಲ ಬೆಲೆ (MSP) ಮತ್ತು ಪಾವತಿಗಳ ಬಗ್ಗೆ ಮಾತ್ರ ಕೇಳಿ."
  },
  ml: {
    title: "🌾 കർഷക സംഭരണ കേന്ദ്രം",
    tagline: "സുതാര്യമായ ധാന്യ സംഭരണവും തത്സമയ ക്യൂ വിവരങ്ങളും",
    register: "കർഷക രജിസ്ട്രേഷൻ",
    login: "മൊബൈൽ ലോഗിൻ",
    sendOtp: "OTP അയക്കുക",
    sendingOtp: "OTP അയക്കുന്നു...",
    verifyOtp: "OTP സ്ഥിരീകരിച്ച് ലോഗിൻ ചെയ്യുക",
    verifyingOtp: "സ്ഥിരീകരിക്കുന്നു...",
    enterOtp: "6 അക്ക OTP നൽകുക",
    resendOtp: "OTP വീണ്ടും അയക്കുക",
    otpSentTo: "OTP അയച്ച നമ്പർ:",
    demoOtpBadge: "ടെസ്റ്റ് OTP:",
    bookSlot: "സ്ലാറ്റ് ബുക്ക് ചെയ്യുക",
    queueStatus: "ക്യൂ നില",
    payment: "പേയ്‌മെന്റും താങ്ങുവിലയും",
    logout: "ലോഗ് ഔട്ട്",
    fullName: "പൂർണ്ണ പേര്",
    phone: "മൊബൈൽ നമ്പർ",
    aadhar: "ആധാർ നമ്പർ",
    address: "വിലാസം",
    bankAccount: "ബാങ്ക് അക്കൗണ്ട് നമ്പർ",
    upi: "UPI ഐഡി",
    registerBtn: "രജിസ്റ്റർ ചെയ്ത് തുടങ്ങുക",
    welcome: "സ്വാഗതം",
    selectSlot: "സ്ലാറ്റ് തിരഞ്ഞെടുക്കുക",
    queuePosition: "നിങ്ങളുടെ ക്യൂ ടോക്കൺ",
    payNow: "പേയ്‌മെന്റ് സ്വീകരിക്കുക",
    help: "കൃഷി സഹായക് (AI)",
    alreadyRegistered: "മുമ്പ് രജിസ്റ്റർ ചെയ്തതാണോ? ലോഗിൻ ചെയ്യുക",
    newFarmer: "പുതിയ കർഷകനാണോ? ഇവിടെ രജിസ്റ്റർ ചെയ്യുക",
    otpVerification: "മൊബൈൽ OTP സ്ഥിരീകരണം",
    enterMobile: "10 അക്ക മൊബൈൽ നമ്പർ നൽകുക",
    phoneRequired: "ശരിയായ മൊബൈൽ നമ്പർ നൽകുക",
    fillAllFields: "എല്ലാ വിവരങ്ങളും പൂരിപ്പിക്കുക",
    chatbotTitle: "🌾 കൃഷി സഹായക് (AI വോയ്‌സ് അസിസ്റ്റന്റ്)",
    chatPlaceholder: "സ്ലാറ്റ്, ക്യൂ, പേയ്‌മെന്റ് എന്നിവയെക്കുറിച്ച് ചോദിക്കുക...",
    voiceListening: "കേൾക്കുന്നു... സംസാരിക്കൂ",
    voiceNotSupported: "വോയ്‌സ് റെക്കഗ്നിഷൻ ലഭ്യമല്ല",
    center: "സംഭരണ കേന്ദ്രം",
    date: "തീയതി",
    time: "സമയം",
    capacity: "ശേഷി",
    status: "നില",
    confirmed: "സ്ഥിരീകരിച്ചു",
    pending: "തീർപ്പുകൽപ്പിക്കാത്തത്",
    completed: "പൂർത്തിയായി",
    totalInQueue: "ക്യൂവിലുള്ള കർഷകർ",
    estimatedWait: "പ്രതീക്ഷിക്കുന്ന സമയം",
    amount: "തുക (₹)",
    transactionId: "ഇടപാട് നമ്പർ",
    paid: "ബാങ്കിലേക്ക് നൽകി (DBT)",
    unpaid: "നടപടിക്രമത്തിലാണ്",
    adminPanel: "അഡ്മിൻ പാനൽ",
    createSlot: "പുതിയ സ്ലാറ്റ് ചേർക്കുക",
    allSlots: "ലഭ്യമായ സ്ലാറ്റുകൾ",
    noSlots: "സ്ലാറ്റുകൾ ലഭ്യമല്ല.",
    noBookings: "ബുക്കിംഗുകൾ ഒന്നും ലഭ്യമല്ല.",
    bookedSuccessfully: "സ്ലാറ്റ് ബുക്ക് ചെയ്തു!",
    loginSuccess: "ലോഗിൻ വിജയകരം!",
    regSuccess: "രജിസ്ട്രേഷൻ വിജയകരം!",
    liveQueueUpdates: "ലൈവ് ക്യൂ അപ്‌ഡേറ്റുകൾ സജീവമാണ്",
    listenVoice: "ശബ്ദം കേൾക്കുക",
    speakMobilePrompt: "മൊബൈൽ നമ്പർ നൽകുക.",
    speakOtpPrompt: "OTP നൽകുക.",
    speakNamePrompt: "മുഴുവൻ പേര് നൽകുക.",
    speakAadharPrompt: "ആധാർ നമ്പർ നൽകുക.",
    speakAddressPrompt: "വിലാസം നൽകുക.",
    speakBankPrompt: "ബാങ്ക് അക്കൗണ്ട് നമ്പർ നൽകുക.",
    speakUpiPrompt: "UPI ഐഡി നൽകുക.",
    ivrTollFree: "📞 ഫോൺ കോൾ വഴി ബുക്കിംഗ്",
    ivrSubtitle: "സ്മാർട്ട്ഫോൺ ഇല്ലാത്ത കർഷകർക്ക് 1800-890-2026 ലേക്ക് വിളിക്കാം",
    dialNow: "വിളിക്കുക (1800-890-2026)",
    strictUnrelatedNotice: "ഈ ചോദ്യം ധാന്യ സംഭരണവുമായി ബന്ധപ്പെട്ടതല്ല. സംഭരണ കേന്ദ്രങ്ങൾ, സ്ലാറ്റ് ബുക്കിംഗ്, ക്യൂ ടോക്കൺ, താങ്ങുവില, പേയ്‌മെന്റ് എന്നിവയെക്കുറിച്ച് മാത്രം ചോദിക്കുക."
  },
  mr: {
    title: "🌾 शेतकरी धान्य खरेदी केंद्र",
    tagline: "पारदर्शक पीक खरेदी आणि थेट रांग ट्रॅकिंग",
    register: "शेतकरी नोंदणी",
    login: "मोबाईल नंबरने लॉगिन",
    sendOtp: "OTP पाठवा",
    sendingOtp: "OTP पाठवला जात आहे...",
    verifyOtp: "OTP सत्यापित करा आणि लॉगिन करा",
    verifyingOtp: "तपासत आहे...",
    enterOtp: "६ अंकी OTP टाका",
    resendOtp: "OTP पुन्हा पाठवा",
    otpSentTo: "OTP पाठवला:",
    demoOtpBadge: "चाचणी OTP:",
    bookSlot: "स्लॉट बुक करा",
    queueStatus: "रांग स्थिती",
    payment: "पेमेंट आणि हमीभाव",
    logout: "लॉगआउट",
    fullName: "पूर्ण नाव",
    phone: "मोबाईल नंबर",
    aadhar: "आधार क्रमांक",
    address: "पत्ता",
    bankAccount: "बँक खाते क्रमांक",
    upi: "UPI आयडी",
    registerBtn: "नोंदणी करा आणि पुढे जा",
    welcome: "स्वागत आहे",
    selectSlot: "खरेदी स्लॉट निवडा",
    queuePosition: "तुमचा टोकन नंबर",
    payNow: "पेमेंट प्राप्त करा",
    help: "कृषी सहाय्यक (AI)",
    alreadyRegistered: "आधीच नोंदणीकृत आहात? लॉगिन करा",
    newFarmer: "नवीन शेतकरी? नोंदणी करा",
    otpVerification: "मोबाईल OTP पडताळणी",
    enterMobile: "१० अंकी मोबाईल नंबर टाका",
    phoneRequired: "कृपया वैध मोबाईल नंबर टाका",
    fillAllFields: "कृपया सर्व माहिती भरा",
    chatbotTitle: "🌾 कृषी सहाय्यक (AI व्हॉईस असिस्टंट)",
    chatPlaceholder: "स्लॉट, रांग, हमीभाव किंवा पेमेंटबद्दल विचारा...",
    voiceListening: "ऐकत आहे... बोला",
    voiceNotSupported: "या ब्राउझरमध्ये व्हॉईस सपोर्ट नाही",
    center: "खरेदी केंद्र",
    date: "तारीख",
    time: "वेळ",
    capacity: "क्षमता",
    status: "स्थिती",
    confirmed: "मंजूर",
    pending: "प्रलंबित",
    completed: "पूर्ण",
    totalInQueue: "रांगेतील शेतकरी संख्या",
    estimatedWait: "अंदाजे वेळ",
    amount: "रक्कम (₹)",
    transactionId: "व्यवहार आयडी",
    paid: "बँकेत जमा झाले (DBT)",
    unpaid: "प्रक्रिया सुरू आहे",
    adminPanel: "प्रशासक पॅनेल",
    createSlot: "नवीन स्लॉट जोडा",
    allSlots: "सर्व स्लॉट",
    noSlots: "कोणतेही स्लॉट उपलब्ध नाहीत.",
    noBookings: "अद्याप कोणतीही बुकिंग नाही.",
    bookedSuccessfully: "स्लॉट यशस्वीरित्या बुक झाला!",
    loginSuccess: "लॉगिन यशस्वी!",
    regSuccess: "नोंदणी यशस्वी!",
    liveQueueUpdates: "थेट रांग अपडेट्स सुरू आहेत",
    listenVoice: "आवाज ऐका",
    speakMobilePrompt: "कृपया १० अंकी मोबाईल नंबर टाका.",
    speakOtpPrompt: "कृपया ६ अंकी OTP टाका.",
    speakNamePrompt: "कृपया पूर्ण नाव टाका.",
    speakAadharPrompt: "कृपया आधार क्रमांक टाका.",
    speakAddressPrompt: "कृपया पत्ता टाका.",
    speakBankPrompt: "कृपया बँक खाते क्रमांक टाका.",
    speakUpiPrompt: "UPI आयडी टाका.",
    ivrTollFree: "📞 फोन कॉलने स्लॉट बुकिंग",
    ivrSubtitle: "स्मार्टफोन नसलेले शेतकरी १८००-८९०-२०२६ वर कॉल करून स्लॉट बुक करू शकतात",
    dialNow: "कॉल करा (१८००-८९०-२०२६)",
    strictUnrelatedNotice: "हा प्रश्न धान्य खरेदीशी संबंधित नाही. कृपया खरेदी केंद्र, स्लॉट बुकिंग, रांग टोकन, हमीभाव आणि पेमेंट संबंधीच प्रश्न विचारा."
  },
  bn: {
    title: "🌾 কৃষক শস্য ক্রয় কেন্দ্র",
    tagline: "স্বচ্ছ শস্য সংগ্রহ এবং রিয়েল-টাইম সারি ট্র্যাকিং",
    register: "কৃষক নিবন্ধন",
    login: "মোবাইল নম্বর দিয়ে লগইন",
    sendOtp: "OTP পাঠান",
    sendingOtp: "OTP পাঠানো হচ্ছে...",
    verifyOtp: "OTP যাচাই করে লগইন করুন",
    verifyingOtp: "যাচাই করা হচ্ছে...",
    enterOtp: "৬ সংখ্যার OTP লিখুন",
    resendOtp: "OTP পুনরায় পাঠান",
    otpSentTo: "OTP পাঠানো হয়েছে:",
    demoOtpBadge: "পরীক্ষার OTP:",
    bookSlot: "স্লট বুক করুন",
    queueStatus: "সারির অবস্থা",
    payment: "পেমেন্ট ও সহায়ক মূল্য",
    logout: "লগআউট",
    fullName: "সম্পূর্ণ নাম",
    phone: "মোবাইল নম্বর",
    aadhar: "আধার নম্বর",
    address: "ঠিকানা",
    bankAccount: "ব্যাঙ্ক অ্যাকাউন্ট নম্বর",
    upi: "UPI আইডি",
    registerBtn: "নিবন্ধন সম্পন্ন করুন",
    welcome: "স্বাগতম",
    selectSlot: "ক্রয় স্লট বেছে নিন",
    queuePosition: "আপনার টোকেন নম্বর",
    payNow: "পেমেন্ট গ্রহণ করুন",
    help: "কৃষি সহায়ক (AI)",
    alreadyRegistered: "ইতিমধ্যে নিবন্ধিত? লগইন করুন",
    newFarmer: "নতুন কৃষক? নিবন্ধন করুন",
    otpVerification: "মোবাইল OTP যাচাইকরণ",
    enterMobile: "১০ সংখ্যার মোবাইল নম্বর দিন",
    phoneRequired: "সঠিক মোবাইল নম্বর লিখুন",
    fillAllFields: "সমস্ত তথ্য পূরণ করুন",
    chatbotTitle: "🌾 কৃষি সহায়ক (AI ভয়েস সহকারী)",
    chatPlaceholder: "স্লট, সারি, পেমেন্ট বা মূল্য সম্পর্কে জিজ্ঞাসা করুন...",
    voiceListening: "শুনছি... কথা বলুন",
    voiceNotSupported: "ভয়েস স্বীকৃতি সমর্থিত নয়",
    center: "সংগ্রহ কেন্দ্র",
    date: "তারিখ",
    time: "সময়",
    capacity: "ধারণক্ষমতা",
    status: "অবস্থা",
    confirmed: "অনুমোদিত",
    pending: "অপেক্ষমান",
    completed: "সম্পন্ন",
    totalInQueue: "সারিতে মোট কৃষক",
    estimatedWait: "আনুমানিক অপেক্ষার সময়",
    amount: "পরিমাণ (₹)",
    transactionId: "লেনদেন আইডি",
    paid: "ব্যাঙ্কে জমা হয়েছে (DBT)",
    unpaid: "প্রক্রিয়াধীন",
    adminPanel: "অ্যাডমিন প্যানেল",
    createSlot: "নতুন স্লট তৈরি করুন",
    allSlots: "উপলব্ধ স্লটসমূহ",
    noSlots: "কোনো স্লট উপলব্ধ নেই।",
    noBookings: "কোনো বুকিং পাওয়া যায়নি।",
    bookedSuccessfully: "স্লট সফলভাবে বুক হয়েছে!",
    loginSuccess: "লগইন সফল হয়েছে!",
    regSuccess: "নিবন্ধন সফল হয়েছে!",
    liveQueueUpdates: "লাইভ সারি আপডেট সংযুক্ত",
    listenVoice: "ভয়েস শুনুন",
    speakMobilePrompt: "আপনার ১০ সংখ্যার মোবাইল নম্বর দিন।",
    speakOtpPrompt: "আপনার ৬ সংখ্যার OTP দিন।",
    speakNamePrompt: "আপনার সম্পূর্ণ নাম লিখুন।",
    speakAadharPrompt: "আপনার আধার নম্বর দিন।",
    speakAddressPrompt: "আপনার ঠিকানা দিন।",
    speakBankPrompt: "আপনার ব্যাঙ্ক অ্যাকাউন্ট নম্বর দিন।",
    speakUpiPrompt: "UPI আইডি দিন।",
    ivrTollFree: "📞 ফোন কলের মাধ্যমে স্লট বুকিং",
    ivrSubtitle: "স্মার্টফোন ছাড়া কৃষকরা ১৮০০-৮৯০-২০২৬ নম্বরে কল করে স্লট বুক করতে পারেন",
    dialNow: "কল করুন (১৮০০-৮৯০-২০২৬)",
    strictUnrelatedNotice: "এই প্রশ্নটি শস্য ক্রয়ের সাথে সম্পর্কিত নয়। অনুগ্রহ করে শুধুমাত্র সংগ্রহ কেন্দ্র, স্লট বুকিং, কিউ টোকেন, সহায়ক মূল্য (MSP) এবং পেমেন্ট সংক্রান্ত প্রশ্ন জিজ্ঞাসা করুন।"
  },
  gu: {
    title: "🌾 ખેડૂત ખરીદ કેન્દ્ર",
    tagline: "પારદર્શક અનાજ ખરીદી અને લાઈવ લાઇન ટ્રેકિંગ",
    register: "ખેડૂત નોંધણી",
    login: "મોબાઇલ નંબરથી લોગિન",
    sendOtp: "OTP મોકલો",
    sendingOtp: "OTP મોકલાઈ રહ્યો છે...",
    verifyOtp: "OTP ચકાસીને લોગિન કરો",
    verifyingOtp: "ચકાસણી ચાલુ છે...",
    enterOtp: "૬ અંકનો OTP દાખલ કરો",
    resendOtp: "OTP ફરી મોકલો",
    otpSentTo: "OTP મોકલેલ નંબર:",
    demoOtpBadge: "ટેસ્ટિંગ OTP:",
    bookSlot: "સ્લોટ બુક કરો",
    queueStatus: "લાઇન સ્થિતિ",
    payment: "ચુકવણી અને ટેકાના ભાવ",
    logout: "લૉગ આઉટ",
    fullName: "પૂરું નામ",
    phone: "મોબાઇલ નંબર",
    aadhar: "આધાર નંબર",
    address: "સરનામું",
    bankAccount: "બેંક ખાતા નંબર",
    upi: "UPI આઈડી",
    registerBtn: "નોંધણી કરો અને આગળ વધો",
    welcome: "સ્વાગત છે",
    selectSlot: "ખરીદ સ્લોટ પસંદ કરો",
    queuePosition: "તમારો ટોકન નંબર",
    payNow: "ચુકવણી મેળવો",
    help: "કૃષિ સહાયક (AI)",
    alreadyRegistered: "પહેલેથી નોંધાયેલા છો? લોગિન કરો",
    newFarmer: "નવા ખેડૂત? અહીં નોંધણી કરો",
    otpVerification: "મોબાઇલ OTP ચકાસણી",
    enterMobile: "૧૦ અંકનો મોબાઇલ નંબર નાખો",
    phoneRequired: "સાચો મોબાઇલ નંબર દાખલ કરો",
    fillAllFields: "કૃપા કરીને બધી વિગતો ભરો",
    chatbotTitle: "🌾 કૃષિ સહાયક (AI વોઇસ સહાયક)",
    chatPlaceholder: "સ્લોટ, લાઇન, ચુકવણી અથવા ટેકાના ભાવ વિશે પૂછો...",
    voiceListening: "સાંભળી રહ્યું છે... બોલો",
    voiceNotSupported: "વોઇસ સપોર્ટ ઉપલબ્ધ નથી",
    center: "ખરીદ કેન્દ્ર",
    date: "તારીખ",
    time: "સમય",
    capacity: "ક્ષમતા",
    status: "સ્થિતિ",
    confirmed: "મંજૂર",
    pending: "બાકી",
    completed: "પૂર્ણ",
    totalInQueue: "લાઇનમાં કુલ ખેડૂતો",
    estimatedWait: "અંદાજિત રાહ જોવાનો સમય",
    amount: "રકમ (₹)",
    transactionId: "ટ્રાન્ઝેક્શન આઈડી",
    paid: "બેંકમાં જમા થઈ ગયું (DBT)",
    unpaid: "પ્રક્રિયામાં છે",
    adminPanel: "એડમિન પેનલ",
    createSlot: "નવો સ્લોટ ઉમેરો",
    allSlots: "બધા સ્લોટ્સ",
    noSlots: "કોઈ સ્લોટ ઉપલબ્ધ નથી.",
    noBookings: "હજુ સુધી કોઈ બુકિંગ નથી.",
    bookedSuccessfully: "સ્લોટ સફળતાપૂર્વક બુક થયો!",
    loginSuccess: "લોગિન સફળ થયું!",
    regSuccess: "નોંધણી સફળ થઈ!",
    liveQueueUpdates: "લાઈવ લાઈન અપડેટ્સ ચાલુ છે",
    listenVoice: "અવાજ સાંભળો",
    speakMobilePrompt: "કૃપા કરીને ૧૦ અંકનો મોબાઇલ નંબર નાખો.",
    speakOtpPrompt: "કૃપા કરીને ૬ અંકનો OTP નાખો.",
    speakNamePrompt: "પૂરું નામ દાખલ કરો.",
    speakAadharPrompt: "આધાર નંબર દાખલ કરો.",
    speakAddressPrompt: "સરનામું દાખલ કરો.",
    speakBankPrompt: "બેંક ખાતા નંબર દાખલ કરો.",
    speakUpiPrompt: "UPI આઈડી દાખલ કરો.",
    ivrTollFree: "📞 ફોન કોલ દ્વારા સ્લોટ બુકિંગ",
    ivrSubtitle: "સ્માર્ટફોન વગરના ખેડૂતો ૧૮૦૦-૮૯૦-૨૦૨૬ પર કોલ કરીને સ્લોટ બુક કરી શકે છે",
    dialNow: "કોલ કરો (૧૮૦૦-૮૯૦-૨૦૨૬)",
    strictUnrelatedNotice: "આ પ્રશ્ન અનાજ ખરીદી સાથે સંબંધિત નથી. કૃપા કરીને માત્ર ખરીદ કેન્દ્ર, સ્લોટ બુકિંગ, લાઇન ટોકન, ટેકાના ભાવ (MSP) અને ચુકવણી અંગેના પ્રશ્નો પૂછો."
  },
  pa: {
    title: "🌾 ਕਿਸਾਨ ਖ਼ਰੀਦ ਕੇਂਦਰ",
    tagline: "ਪਾਰਦਰਸ਼ੀ ਫ਼ਸਲ ਖ਼ਰੀਦ ਅਤੇ ਲਾਈਵ ਕਤਾਰ ਟਰੈਕਿੰਗ",
    register: "ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    login: "ਮੋਬਾਈਲ ਨੰਬਰ ਨਾਲ ਲੌਗਇਨ",
    sendOtp: "OTP ਭੇਜੋ",
    sendingOtp: "OTP ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
    verifyOtp: "OTP ਤਸਦੀਕ ਕਰੋ ਤੇ ਲੌਗਇਨ ਕਰੋ",
    verifyingOtp: "ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ...",
    enterOtp: "6 ਅੰਕਾਂ ਦਾ OTP ਦਰਜ ਕਰੋ",
    resendOtp: "OTP ਦੁਬਾਰਾ ਭੇਜੋ",
    otpSentTo: "OTP ਇਸ ਨੰਬਰ 'ਤੇ ਭੇਜਿਆ ਗਿਆ:",
    demoOtpBadge: "ਟੈਸਟਿੰਗ OTP:",
    bookSlot: "ਸਲਾਟ ਬੁੱਕ ਕਰੋ",
    queueStatus: "ਕਤਾਰ ਸਥਿਤੀ",
    payment: "ਭੁਗਤਾਨ ਅਤੇ ਐਮਐਸਪੀ",
    logout: "ਲੌਗ ਆਉਟ",
    fullName: "ਪੂਰਾ ਨਾਮ",
    phone: "ਮੋਬਾਈਲ ਨੰਬਰ",
    aadhar: "ਆਧਾਰ ਨੰਬਰ",
    address: "ਪਤਾ",
    bankAccount: "ਬੈਂਕ ਖਾਤਾ ਨੰਬਰ",
    upi: "UPI ਆਈਡੀ",
    registerBtn: "ਰਜਿਸਟਰ ਕਰੋ ਅਤੇ ਸ਼ੁਰੂ ਕਰੋ",
    welcome: "ਜੀ ਆਇਆਂ ਨੂੰ",
    selectSlot: "ਖ਼ਰੀਦ ਸਲਾਟ ਚੁਣੋ",
    queuePosition: "ਤੁਹਾਡਾ ਟੋਕਨ ਨੰਬਰ",
    payNow: "ਭੁਗਤਾਨ ਪ੍ਰਾਪਤ ਕਰੋ",
    help: "ਕ੍ਰਿਸ਼ੀ ਸਹਾਇਕ (AI)",
    alreadyRegistered: "ਪਹਿਲਾਂ ਤੋਂ ਰਜਿਸਟਰਡ ਹੋ? ਲੌਗਇਨ ਕਰੋ",
    newFarmer: "ਨਵੇਂ ਕਿਸਾਨ? ਇੱਥੇ ਰਜਿਸਟਰ ਕਰੋ",
    otpVerification: "ਮੋਬਾਈਲ OTP ਪੁਸ਼ਟੀ",
    enterMobile: "10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ",
    phoneRequired: "ਕਿਰਪਾ ਕਰਕੇ ਸਹੀ ਮੋਬਾਈਲ ਨੰਬਰ ਭਰੋ",
    fillAllFields: "ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੀ ਜਾਣਕਾਰੀ ਭਰੋ",
    chatbotTitle: "🌾 ਕ੍ਰਿਸ਼ੀ ਸਹਾਇਕ (AI ਵੌਇਸ ਅਸਿਸਟੈਂਟ)",
    chatPlaceholder: "ਸਲਾਟ, ਕਤਾਰ, ਭੁਗਤਾਨ ਜਾਂ ਐਮਐਸਪੀ ਬਾਰੇ ਪੁੱਛੋ...",
    voiceListening: "ਸੁਣ ਰਿਹਾ ਹੈ... ਬੋਲੋ",
    voiceNotSupported: "ਵੌਇਸ ਪਛਾਣ ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਉਪਲਬਧ ਨਹੀਂ ਹੈ",
    center: "ਖ਼ਰੀਦ ਕੇਂਦਰ",
    date: "ਮਿਤੀ",
    time: "ਸਮਾਂ",
    capacity: "ਸਮਰੱਥਾ",
    status: "ਸਥਿਤੀ",
    confirmed: "ਪੁਸ਼ਟੀ ਹੋਈ",
    pending: "ਬਕਾਇਆ",
    completed: "ਮੁਕੰਮਲ",
    totalInQueue: "ਕਤਾਰ ਵਿੱਚ ਕੁੱਲ ਕਿਸਾਨ",
    estimatedWait: "ਅੰਦਾਜ਼ਨ ਉਡੀਕ ਸਮਾਂ",
    amount: "ਰਕਮ (₹)",
    transactionId: "ਲੈਣ-ਦੇਣ ਨੰਬਰ",
    paid: "ਬੈਂਕ ਵਿੱਚ ਜਮ੍ਹਾ ਹੋ ਗਿਆ (DBT)",
    unpaid: "ਕਾਰਵਾਈ ਚੱਲ ਰਹੀ ਹੈ",
    adminPanel: "ਐਡਮਿਨ ਪੈਨਲ",
    createSlot: "ਨਵਾਂ ਸਲਾਟ ਬਣਾਓ",
    allSlots: "ਸਾਰੇ ਉਪਲਬਧ ਸਲਾਟ",
    noSlots: "ਕੋਈ ਸਲਾਟ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।",
    noBookings: "ਕੋਈ ਬੁਕਿੰਗ ਨਹੀਂ ਮਿਲੀ।",
    bookedSuccessfully: "ਸਲਾਟ ਸਫਲਤਾਪੂਰਵਕ ਬੁੱਕ ਹੋ ਗਿਆ!",
    loginSuccess: "ਲੌਗਇਨ ਸਫਲ ਰਿਹਾ!",
    regSuccess: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸਫਲ ਰਹੀ!",
    liveQueueUpdates: "ਲਾਈਵ ਕਤਾਰ ਅੱਪਡੇਟ ਚਾਲੂ ਹੈ",
    listenVoice: "ਆਵਾਜ਼ ਸੁਣੋ",
    speakMobilePrompt: "ਕਿਰਪਾ ਕਰਕੇ 10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਭਰੋ।",
    speakOtpPrompt: "ਕਿਰਪਾ ਕਰਕੇ 6 ਅੰਕਾਂ ਦਾ OTP ਭਰੋ।",
    speakNamePrompt: "ਪੂਰਾ ਨਾਮ ਭਰੋ।",
    speakAadharPrompt: "ਆਧਾਰ ਨੰਬਰ ਭਰੋ।",
    speakAddressPrompt: "ਪਤਾ ਭਰੋ।",
    speakBankPrompt: "ਬੈਂਕ ਖਾਤਾ ਨੰਬਰ ਭਰੋ।",
    speakUpiPrompt: "UPI ਆਈਡੀ ਭਰੋ।",
    ivrTollFree: "📞 ਫ਼ੋਨ ਕਾਲ ਰਾਹੀਂ ਸਲਾਟ ਬੁਕਿੰਗ",
    ivrSubtitle: "ਸਮਾਰਟਫ਼ੋਨ ਤੋਂ ਬਿਨਾਂ ਕਿਸਾਨ 1800-890-2026 'ਤੇ ਕਾਲ ਕਰਕੇ ਸਲਾਟ ਬੁੱਕ ਕਰ ਸਕਦੇ ਹਨ",
    dialNow: "ਕਾਲ ਕਰੋ (1800-890-2026)",
    strictUnrelatedNotice: "ਇਹ ਸਵਾਲ ਫ਼ਸਲ ਖ਼ਰੀਦ ਨਾਲ ਸੰਬੰਧਿਤ ਨਹੀਂ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਸਿਰਫ਼ ਖ਼ਰੀਦ ਕੇਂਦਰ, ਸਲਾਟ ਬੁਕਿੰਗ, ਕਤਾਰ ਟੋਕਨ, ਐਮਐਸਪੀ ਅਤੇ ਭੁਗਤਾਨ ਬਾਰੇ ਹੀ ਪੁੱਛੋ।"
  },
  or: {
    title: "🌾 କୃଷକ ଶସ୍ୟ ସଂଗ୍ରହ କେନ୍ଦ୍ର",
    tagline: "ସ୍ୱଚ୍ଛ ଶସ୍ୟ କ୍ରୟ ଏବଂ ଲାଇଭ୍ ଧାଡ଼ି ଟ୍ରାକିଂ",
    register: "କୃଷକ ପଞ୍ଜୀକରଣ",
    login: "ମୋବାଇଲ୍ ନମ୍ବର ଲଗଇନ୍",
    sendOtp: "OTP ପଠାନ୍ତୁ",
    sendingOtp: "OTP ପଠାଯାଉଛି...",
    verifyOtp: "OTP ଯାଞ୍ଚ କରି ଲଗଇନ୍ କରନ୍ତୁ",
    verifyingOtp: "ଯାଞ୍ଚ ହେଉଛି...",
    enterOtp: "୬ ଅଙ୍କ ବିଶିଷ୍ଟ OTP ଦିଅନ୍ତୁ",
    resendOtp: "OTP ପୁନଃ ପଠାନ୍ତୁ",
    otpSentTo: "OTP ପଠାଯାଇଥିବା ନମ୍ବର:",
    demoOtpBadge: "ପରୀକ୍ଷା OTP:",
    bookSlot: "ସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ",
    queueStatus: "ଧାଡ଼ି ସ୍ଥିତି",
    payment: "ଦେୟ ଏବଂ ସହାୟକ ମୂଲ୍ୟ",
    logout: "ଲଗ୍ ଆଉଟ୍",
    fullName: "ସମ୍ପୂର୍ଣ୍ଣ ନାମ",
    phone: "ମୋବାଇଲ୍ ନମ୍ବର",
    aadhar: "ଆଧାର ନମ୍ବର",
    address: "ଠିକଣା",
    bankAccount: "ବ୍ୟାଙ୍କ ଖାତା ନମ୍ବର",
    upi: "UPI ଆଇଡି",
    registerBtn: "ପଞ୍ଜୀକରଣ କରି ଆଗକୁ ବଢ଼ନ୍ତୁ",
    welcome: "ସ୍ୱାଗତ",
    selectSlot: "ସଂଗ୍ରହ ସ୍ଲଟ୍ ଚୟନ କରନ୍ତୁ",
    queuePosition: "ଆପଣଙ୍କ ଟୋକନ୍ ନମ୍ବର",
    payNow: "ଦେୟ ଗ୍ରହଣ କରନ୍ତୁ",
    help: "କୃଷି ସହାୟକ (AI)",
    alreadyRegistered: "ପୂର୍ବରୁ ପଞ୍ଜୀକୃତ କି? ଲଗଇନ୍ କରନ୍ତୁ",
    newFarmer: "ନୂତନ କୃଷକ? ଏଠାରେ ପଞ୍ଜୀକରଣ କରନ୍ତୁ",
    otpVerification: "ମୋବାଇଲ୍ OTP ଯାଞ୍ଚ",
    enterMobile: "୧୦ ଅଙ୍କ ବିଶିଷ୍ଟ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ",
    phoneRequired: "ଦୟାକରି ସଠିକ୍ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ",
    fillAllFields: "ଦୟାକରି ସମସ୍ତ ବିବରଣୀ ପୂରଣ କରନ୍ତୁ",
    chatbotTitle: "🌾 କୃଷି ସହାୟକ (AI ଭଏସ୍ ସହାୟକ)",
    chatPlaceholder: "ସ୍ଲଟ୍, ଧାଡ଼ି, ଦେୟ କିମ୍ବା ମୂଲ୍ୟ ବିଷୟରେ ପଚାରନ୍ତୁ...",
    voiceListening: "ଶୁଣୁଛି... କୁହନ୍ତୁ",
    voiceNotSupported: "ଏହି ବ୍ରାଉଜରରେ ଭଏସ୍ ସମର୍ଥିତ ନୁହେଁ",
    center: "ସଂଗ୍ରହ କେନ୍ଦ୍ର",
    date: "ତାରିଖ",
    time: "ସମୟ",
    capacity: "କ୍ଷମତା",
    status: "ସ୍ଥିତି",
    confirmed: "ନିଶ୍ଚିତ",
    pending: "ବକେୟା",
    completed: "ସମ୍ପୂର୍ଣ୍ଣ",
    totalInQueue: "ଧାଡ଼ିରେ କୃଷକ",
    estimatedWait: "ଅପେକ୍ଷା ସମୟ",
    amount: "ପରିମାଣ (₹)",
    transactionId: "କାରବାର ID",
    paid: "ବ୍ୟାଙ୍କରେ ଜମା ହୋଇଛି (DBT)",
    unpaid: "ପ୍ରକ୍ରିୟାଧୀନ",
    adminPanel: "ପ୍ରଶାସନିକ ପ୍ୟାନେଲ୍",
    createSlot: "ନୂତନ ସ୍ଲଟ୍ ଯୋଡ଼ନ୍ତୁ",
    allSlots: "ସମସ୍ତ ସ୍ଲଟ୍",
    noSlots: "କୌଣସି ସ୍ଲଟ୍ ଉପଲବ୍ଧ ନାହିଁ।",
    noBookings: "କୌଣସି ବୁକିଂ ମିଳିଲା ନାହିଁ।",
    bookedSuccessfully: "ସ୍ଲଟ୍ ସଫଳତାର ସହିତ ବୁକ୍ ହେଲା!",
    loginSuccess: "ଲଗଇନ୍ ସଫଳ ହେଲା!",
    regSuccess: "ପଞ୍ଜୀକରଣ ସଫଳ ହେଲା!",
    liveQueueUpdates: "ଲାଇଭ୍ ଧାଡ଼ି ଅପଡେଟ୍ ସକ୍ରିୟ ଅଛି",
    listenVoice: "ଭଏସ୍ ଶୁଣନ୍ତୁ",
    speakMobilePrompt: "ଦୟାକରି ୧୦ ଅଙ୍କ ବିଶିଷ୍ଟ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ।",
    speakOtpPrompt: "୬ ଅଙ୍କ ବିଶିଷ୍ଟ OTP ଦିଅନ୍ତୁ।",
    speakNamePrompt: "ସମ୍ପୂର୍ଣ୍ଣ ନାମ ଦିଅନ୍ତୁ।",
    speakAadharPrompt: "ଆଧାର ନମ୍ବର ଦିଅନ୍ତୁ।",
    speakAddressPrompt: "ଠିକଣା ଦିଅନ୍ତୁ।",
    speakBankPrompt: "ବ୍ୟାଙ୍କ ଖାତା ନମ୍ବର ଦିଅନ୍ତୁ।",
    speakUpiPrompt: "UPI ଆଇଡି ଦିଅନ୍ତୁ।",
    ivrTollFree: "📞 ଫୋନ୍ କଲ୍ ମାଧ୍ୟମରେ ସ୍ଲଟ୍ ବୁକିଂ",
    ivrSubtitle: "ସ୍ମାର୍ଟଫୋନ୍ ନଥିବା କୃଷକମାନେ ୧୮୦୦-୮୯୦-୨୦୨୬ ରେ କଲ୍ କରି ସ୍ଲଟ୍ ବୁକ୍ କରିପାରିବେ",
    dialNow: "କଲ୍ କରନ୍ତୁ (୧୮୦୦-୮୯୦-୨୦୨୬)",
    strictUnrelatedNotice: "ଏହି ପ୍ରଶ୍ନଟି ଶସ୍ୟ କ୍ରୟ ସହିତ ସମ୍ପର୍କିତ ନୁହେଁ। ଦୟାକରି କେବଳ କ୍ରୟ କେନ୍ଦ୍ର, ସ୍ଲଟ୍ ବୁକିଂ, ଧାଡ଼ି ଟୋକନ୍, MSP ମୂଲ୍ୟ ଏବଂ ଦେୟ ବିଷୟରେ ପଚାରନ୍ତୁ।"
  }
};

export const chatbotResponses = {
  en: {
    greetings: [
      "Namaste Kisan brother! I am your dedicated Krishi Sahayak for Procurement Centers. How may I help you today?",
      "Welcome! Ask me about Procurement Center locations, slot booking, live queue tokens, MSP rates, and DBT bank payments."
    ],
    slotBooking: "To book a procurement slot, go to the 'Book Slot' tab, select your nearby center, choose date & time, and confirm. If you don't have a smartphone, dial toll-free 1800-890-2026.",
    queue: "You can track your live queue token and estimated wait time in the 'Queue Status' tab.",
    payment: "After grain inspection and weighing at the mandi, your payment is sanctioned by the Procurement Admin and credited directly into your linked bank account via PFMS DBT within 24-48 hours.",
    msp: "Government Minimum Support Prices (MSP 2026): Paddy (Common): ₹2,300/q, Paddy (Grade A): ₹2,320/q, Wheat: ₹2,275/q, Cotton: ₹7,121/q, Maize: ₹2,090/q, Soyabean: ₹4,892/q, Pulses: ₹8,682/q.",
    centers: "Procurement centers operate from 08:30 AM to 05:30 PM. Each center has grain moisture testing equipment (max 17% allowed for Paddy) and digital weighing scales.",
    documents: "Required documents at mandi: 1) Aadhaar Card, 2) Bank Passbook, 3) Pattadar Passbook / Land Record (Rythu Bandhu ID).",
    ivrPhone: "No smartphone? Simply call our toll-free number 1800-890-2026 from any mobile or landline phone to book your slot in your preferred language.",
    support: "Kisan Toll-Free Helpline: 1800-180-1551 (Open 6 AM to 10 PM daily).",
    unrelated: "This question is not related to crop procurement. Please ask only queries regarding procurement centers, slot booking, live queue tokens, MSP rates, and farmer payments."
  },
  te: {
    greetings: [
      "నమస్కారం రైతు సోదరులారా! నేను మీ ధాన్య సేకరణ కృషి సహాయక్ AI ని. సేకరణ కేంద్రాలు, స్లాట్లు, మద్దతు ధర గురించి మీకు ఎలా సహాయపడగలను?",
      "స్వాగతం! ధాన్య సేకరణ కేంద్రాలు, స్లాట్ బుకింగ్, క్యూ టోకెన్లు, మద్దతు ధర (MSP) మరియు బ్యాంక్ చెల్లింపుల గురించి అడగండి."
    ],
    slotBooking: "సేకరణ స్లాట్ బుక్ చేయడానికి 'స్లాట్ బుక్ చేయండి' ట్యాబ్‌కు వెళ్లి కేంద్రం, తేదీ మరియు సమయాన్ని ఎంచుకోండి. స్మార్ట్‌ఫోన్ లేకపోతే 1800-890-2026 కు కాల్ చేయండి.",
    queue: "మీ ప్రస్తుత క్యూ టోకెన్ నంబర్ మరియు ఎంత సమయం వేచి ఉండాలో 'క్యూ స్థితి' విభాగంలో ప్రత్యక్షంగా చూడవచ్చు.",
    payment: "మండీలో ధాన్యం తూకం పూర్తయిన తర్వాత అడ్మిన్ మంజూరు చేసిన మొత్తం 24-48 గంటల్లో మీ ఆధార్ లింక్ అయిన బ్యాంక్ ఖాతాలో DBT ద్వారా జమ అవుతుంది.",
    msp: "ప్రభుత్వ మద్దతు ధరలు (MSP 2026): వరి (సాధారణ): ₹2,300/క్వింటా, వరి (గ్రేడ్ A): ₹2,320/క్వింటా, పత్తి: ₹7,121/క్వింటా, మొక్కజొన్న: ₹2,090/క్వింటా, సోయాబీన్: ₹4,892/క్వింటా.",
    centers: "ధాన్య సేకరణ కేంద్రాలు ఉదయం 8:30 నుండి సాయంత్రం 5:30 వరకు పనిచేస్తాయి. తేమ శాతం గరిష్టంగా 17% లోపు ఉండాలి.",
    documents: "తీసుకురావలసిన పత్రాలు: 1) ఆధార్ కార్డు, 2) బ్యాంక్ పాస్‌బుక్, 3) పట్టాదారు పాస్‌బుక్ / రైతు బంధు ID.",
    ivrPhone: "స్మార్ట్‌ఫోన్ లేదా? ఏ మొబైల్ లేదా ల్యాండ్‌లైన్ నుండి అయినా 1800-890-2026 టోల్‌ఫ్రీ నంబర్‌కు కాల్ చేసి మీ మాతృభాషలో స్లాట్ బుక్ చేసుకోవచ్చు.",
    support: "రైతు టోల్‌ఫ్రీ హెల్ప్‌లైన్: 1800-180-1551 (ఉదయం 6 నుండి రాత్రి 10 వరకు).",
    unrelated: "ఈ ప్రశ్న ధాన్య సేకరణకు సంబంధించినది కాదు. దయచేసి సేకరణ కేంద్రాలు, స్లాట్ బుకింగ్, క్యూ టోకెన్లు, మద్దతు ధర (MSP) మరియు రైతు చెల్లింపుల గురించి మాత్రమే అడగండి."
  },
  hi: {
    greetings: [
      "नमस्कार किसान भाइयों एवं बहनों! मैं आपका फसल खरीद कृषि सहायक AI हूँ। मैं आपकी क्या मदद कर सकता हूँ?",
      "प्रणाम! खरीद केंद्र, स्लॉट बुकिंग, लाइव कतार टोकन, एमएसपी दर और बैंक डीबीटी भुगतान के बारे में पूछें।"
    ],
    slotBooking: "स्लॉट बुक करने के लिए 'स्लॉट बुक करें' टैब पर जाएं और नजदीकी केंद्र, तिथि व समय चुनें। यदि स्मार्टफोन नहीं है तो टोल-फ्री 1800-890-2026 पर कॉल करें।",
    queue: "आप 'कतार स्थिति' टैब में अपना लाइव टोकन नंबर और अनुमानित प्रतीक्षा समय देख सकते हैं।",
    payment: "मंडी में फसल की तौल के बाद खरीद अधिकारी द्वारा स्वीकृत राशि 24 से 48 घंटे में सीधे आपके बैंक खाते में डीबीटी द्वारा भेज दी जाती है।",
    msp: "सरकारी न्यूनतम समर्थन मूल्य (MSP): धान (सामान्य): ₹2,300/क्विंटल, धान (ग्रेड A): ₹2,320/क्विंटल, गेहूं: ₹2,275/क्विंटल, कपास: ₹7,121/क्विंटल, मक्का: ₹2,090/क्विंटल।",
    centers: "खरीद केंद्र सुबह 8:30 से शाम 5:30 तक खुले रहते हैं। धान में नमी अधिकतम 17% होनी चाहिए।",
    documents: "मंडी में आवश्यक दस्तावेज: 1) आधार कार्ड, 2) बैंक पासबुक, 3) भूमि रिकॉर्ड / किसान क्रेडिट पासबुक।",
    ivrPhone: "बिना स्मार्टफोन के किसान टोल-फ्री नंबर 1800-890-2026 पर कॉल करके अपनी पसंदीदा भाषा में स्लॉट बुक कर सकते हैं।",
    support: "किसान कॉल सेंटर हेल्पलाइन: 1800-180-1551 (टोल फ्री)।",
    unrelated: "यह प्रश्न फसल खरीद से संबंधित नहीं है। कृपया केवल खरीद केंद्र, स्लॉट बुकिंग, कतार टोकन, एमएसपी दर और किसान भुगतान से संबंधित प्रश्न ही पूछें।"
  },
  ta: {
    greetings: [
      "வணக்கம் விவசாய பெருமக்களே! நான் உங்கள் கொள்முதல் விவசாய AI உதவியாளர்.",
      "கொள்முதல் மையங்கள், முன்பதிவு, வரிசை டோக்கன், MSP விலை மற்றும் வங்கி பரிவர்த்தனை பற்றி கேளுங்கள்."
    ],
    slotBooking: "முன்பதிவு செய்ய 'இடத்தை முன்பதிவு செய்' பகுதிக்கு செல்லவும். ஸ்மார்ட்போன் இல்லையெனில் 1800-890-2026 என்ற எண்ணை அழைக்கவும்.",
    queue: "உங்கள் டோக்கன் நிலையை 'வரிசை நிலை' பகுதியில் நேரலையாக பார்க்கலாம்.",
    payment: "தானிய எடை மற்றும் தர பரிசோதனைக்கு பிறகு தொகை நேரடியாக உங்கள் வங்கி கணக்கில் DBT மூலம் வரவு வைக்கப்படும்.",
    msp: "அரசு MSP விலை: நெல்: ₹2,300/குவிண்டால், பருத்தி: ₹7,121/குவிண்டால், கோதுமை: ₹2,275/குவிண்டால்.",
    centers: "மையங்கள் காலை 8:30 முதல் மாலை 5:30 வரை செயல்படும்.",
    documents: "தேவையான ஆவணங்கள்: ஆதார் அட்டை, வங்கி கணக்கு புத்தகம், நில ஆவணம்.",
    ivrPhone: "1800-890-2026 என்ற இலவச தொலைபேசி எண்ணை அழைத்து முன்பதிவு செய்யலாம்.",
    support: "விவசாயி உதவி எண்: 1800-180-1551.",
    unrelated: "இந்த கேள்வி தானிய கொள்முதலுடன் தொடர்புடையது அல்ல. கொள்முதல் மையம், முன்பதிவு, வரிசை டோக்கன், MSP விலை மற்றும் பணம் செலுத்துதல் பற்றிய கேள்விகளை மட்டும் கேட்கவும்."
  },
  kn: {
    greetings: [
      "ನಮಸ್ಕಾರ ರೈತ ಬಾಂಧವರೇ! ನಾನು ಧಾನ್ಯ ಖರೀದಿ ಕೃಷಿ ಸಹಾಯಕ AI.",
      "ಖರೀದಿ ಕೇಂದ್ರ, ಸ್ಲಾಟ್ ಕಾಯ್ದಿರಿಸುವಿಕೆ, ಸರದಿ ಟೋಕನ್ ಮತ್ತು ಬೆಂಬಲ ಬೆಲೆ ಬಗ್ಗೆ ಕೇಳಿ."
    ],
    slotBooking: "ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಲು 'ಸ್ಲಾಟ್ ಕಾಯ್ದಿರಿಸಿ' ಮೆನುವಿಗೆ ಹೋಗಿ. ಫೋನ್ ಇಲ್ಲದಿದ್ದರೆ 1800-890-2026 ಗೆ ಕರೆ ಮಾಡಿ.",
    queue: "ನಿಮ್ಮ ಲೈವ್ ಟೋಕನ್ ಸಂಖ್ಯೆಯನ್ನು 'ಸರದಿ ಸಾಲಿನ ಸ್ಥಿತಿ'ಯಲ್ಲಿ ಪರಿಶೀಲಿಸಿ.",
    payment: "ತೂಕದ ನಂತರ ಹಣವು ನೇರವಾಗಿ DBT ಮೂಲಕ ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮೆಯಾಗುತ್ತದೆ.",
    msp: "ಸರ್ಕಾರಿ ಬೆಂಬಲ ಬೆಲೆ: ಭತ್ತ: ₹2,300/ಕ್ವಿಂಟಾಲ್, ಹತ್ತಿ: ₹7,121/ಕ್ವಿಂಟಾಲ್, ಮೆಕ್ಕೆಜೋಳ: ₹2,090/ಕ್ವಿಂಟಾಲ್.",
    centers: "ಖರೀದಿ ಕೇಂದ್ರಗಳು ಬೆಳಗ್ಗೆ 8:30 ರಿಂದ ಸಂಜೆ 5:30 ರವರೆಗೆ ತೆರೆದಿರುತ್ತವೆ.",
    documents: "ಅಗತ್ಯ ದಾಖಲೆಗಳು: ಆಧಾರ್ ಕಾರ್ಡ್, ಬ್ಯಾಂಕ್ ಪಾಸ್‌ಬುಕ್, ಪಹಣಿ ಪತ್ರ.",
    ivrPhone: "ಸ್ಮಾರ್ಟ್‌ಫೋನ್ ಇಲ್ಲದಿದ್ದರೆ 1800-890-2026 ಗೆ ಕರೆ ಮಾಡಿ ಧ್ವನಿ ಮೂಲಕ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ.",
    support: "ಕಿಸಾನ್ ಸಹಾಯವಾಣಿ: 1800-180-1551.",
    unrelated: "ಈ ಪ್ರಶ್ನೆಯು ಧಾನ್ಯ ಖರೀದಿಗೆ ಸಂಬಂಧಿಸಿಲ್ಲ. ದಯವಿಟ್ಟು ಖರೀದಿ ಕೇಂದ್ರ, ಸ್ಲಾಟ್ ಬುಕಿಂಗ್, ಸರದಿ ಟೋಕನ್, ಬೆಂಬಲ ಬೆಲೆ (MSP) ಮತ್ತು ಪಾವತಿಗಳ ಬಗ್ಗೆ ಮಾತ್ರ ಕೇಳಿ."
  },
  ml: {
    greetings: [
      "നമസ്കാരം കർഷക സുഹൃത്തുക്കളെ! ഞാൻ സംഭരണ കൃഷി സഹായക് AI ആണ്.",
      "സംഭരണ കേന്ദ്രം, സ്ലാറ്റ് ബുക്കിംഗ്, ക്യൂ ടോക്കൺ, താങ്ങുവില എന്നിവയെക്കുറിച്ച് ചോദിക്കുക."
    ],
    slotBooking: "'സ്ലാറ്റ് ബുക്ക് ചെയ്യുക' എന്നതിൽ ക്ലിക്ക് ചെയ്ത് ബുക്ക് ചെയ്യാം. ഫോൺ ഇല്ലെങ്കിൽ 1800-890-2026 വിളിക്കുക.",
    queue: "നിങ്ങളുടെ ടോക്കൺ നമ്പർ 'ക്യൂ നില' യിൽ തത്സമയം കാണാം.",
    payment: "തൂക്കത്തിന് ശേഷം തുക ബാങ്ക് അക്കൗണ്ടിലേക്ക് നേരിട്ട് DBT വഴി എത്തും.",
    msp: "താങ്ങുവില: നെല്ല്: ₹2,300/ക്വിന്റൽ, പരുത്തി: ₹7,121/ക്വിന്റൽ.",
    centers: "രാവിലെ 8:30 മുതൽ വൈകുന്നേരം 5:30 വരെ കേന്ദ്രങ്ങൾ പ്രവർത്തിക്കും.",
    documents: "ആവശ്യമായ രേഖകൾ: ആധാർ, ബാങ്ക് പാസ്ബുക്ക്, കരം രസീത്.",
    ivrPhone: "1800-890-2026 ലേക്ക് വിളിച്ചു ഫോൺ വഴി ബുക്ക് ചെയ്യാം.",
    support: "ഹെൽപ്പ്‌ലൈൻ: 1800-180-1551.",
    unrelated: "ഈ ചോദ്യം ധാന്യ സംഭരണവുമായി ബന്ധപ്പെട്ടതല്ല. സംഭരണ കേന്ദ്രങ്ങൾ, സ്ലാറ്റ് ബുക്കിംഗ്, ക്യൂ ടോക്കൺ, താങ്ങുവില, പേയ്‌മെന്റ് എന്നിവയെക്കുറിച്ച് മാത്രം ചോദിക്കുക."
  },
  mr: {
    greetings: [
      "नमस्कार शेतकरी बांधवांनो! मी धान्य खरेदी कृषी सहाय्यक AI आहे.",
      "खरेदी केंद्र, स्लॉट बुकिंग, थेट रांग टोकन आणि हमीभाव माहितीसाठी विचारा."
    ],
    slotBooking: "'स्लॉट बुक करा' विभागात जाऊन वेळ निवडा किंवा १८००-८९०-२०२६ वर कॉल करा.",
    queue: "तुमचा टोकन क्रमांक 'रांग स्थिती' विभागात थेट पाहू शकता.",
    payment: "तौल झाल्यानंतर रक्कम थेट तुमच्या बँक खात्यात डीबीटीद्वारे जमा होते.",
    msp: "हमीभाव (MSP): धान: ₹२,३००/क्विंटल, कापूस: ₹७,१२१/क्विंटल, मका: ₹२,०९०/क्विंटल.",
    centers: "केंद्रे सकाळी ८:३० ते संध्याकाळी ५:३० पर्यंत सुरू असतात.",
    documents: "आवश्यक कागदपत्रे: आधार कार्ड, बँक पासबुक, ७/१२ उतारा.",
    ivrPhone: "स्मार्टफोन नसल्यास १८००-८९०-२०२६ वर फोन करून स्लॉट बुक करा.",
    support: "किसान कॉल सेंटर: १८००-१८०-१५५१.",
    unrelated: "हा प्रश्न धान्य खरेदीशी संबंधित नाही. कृपया खरेदी केंद्र, स्लॉट बुकिंग, रांग टोकन, हमीभाव आणि पेमेंट संबंधीच प्रश्न विचारा."
  },
  bn: {
    greetings: [
      "নমস্কার কৃষক ভাই ও বোনেরা! আমি শস্য সংগ্রহ কৃষি সহায়ক AI।",
      "সংগ্রহ কেন্দ্র, স্লট বুকিং, কিউ টোকেন এবং সহায়ক মূল্য (MSP) সম্পর্কে জিজ্ঞাসা করুন।"
    ],
    slotBooking: "'স্লট বুক করুন' অংশে যান বা ১৮০০-৮৯০-২০২৬ নম্বরে কল করে বুক করুন।",
    queue: "'সারির অবস্থা' অংশে লাইভ টোকেন দেখতে পারেন।",
    payment: "শস্য পরীক্ষার পর সম্পূর্ণ অর্থ সরাসরি DBT মাধ্যমে ব্যাঙ্ক অ্যাকাউন্টে জমা হবে।",
    msp: "সহায়ক মূল্য: ধান: ₹২,৩০০/কুইন্টাল, গম: ₹২,২৭৫/কুইন্টাল, তুলা: ₹৭,১২১/কুইন্টাল।",
    centers: "কেন্দ্রগুলি সকাল ৮:৩০ থেকে বিকাল ৫:৩০ পর্যন্ত খোলা থাকে।",
    documents: "প্রয়োজনীয় নথি: আধার কার্ড, ব্যাঙ্ক পাসবই, জমির খতিয়ান।",
    ivrPhone: "১৮০০-৮৯০-২০২৬ টোল-ফ্রি নম্বরে কল করে স্লট বুক করতে পারেন।",
    support: "কৃষক হেল্পলাইন: ১৮০০-১৮০-১৫৫১।",
    unrelated: "এই প্রশ্নটি শস্য ক্রয়ের সাথে সম্পর্কিত নয়। অনুগ্রহ করে শুধুমাত্র সংগ্রহ কেন্দ্র, স্লট বুকিং, কিউ টোকেন, সহায়ক মূল্য (MSP) এবং পেমেন্ট সংক্রান্ত প্রশ্ন জিজ্ঞাসা করুন।"
  },
  gu: {
    greetings: [
      "નમસ્તે ખેડૂત મિત્રો! હું અનાજ ખરીદ સહાયક AI છું.",
      "ખરીદ કેન્દ્ર, સ્લોટ બુકિંગ, લાઇન ટોકન અને ટેકાના ભાવ વિશે પૂછો."
    ],
    slotBooking: "'સ્લોટ બુક કરો' માં જઈને બુક કરો અથવા ૧૮૦૦-૮૯૦-૨૦૨૬ પર કોલ કરો.",
    queue: "'લાઇન સ્થિતિ' માં તમારો ટોકન નંબર તપાસો.",
    payment: "તોલણી પછી રકમ સીધી બેંક ખાતામાં DBT દ્વારા જમા થાય છે.",
    msp: "ટેકાના ભાવ: ડાંગર: ₹૨,૩૦૦/ક્વિન્ટલ, કપાસ: ₹૭,૧૨૧/ક્વિન્ટલ.",
    centers: "કેન્દ્રો સવારે ૮:૩০ થી સાંજે ૫:૩૦ સુધી ચાલુ રહે છે.",
    documents: "જરૂરી દસ્તાવેજો: આધાર કાર્ડ, બેંક પાસબુક, ૭/૧૨ નો દાખલો.",
    ivrPhone: "૧૮૦૦-૮૯૦-૨૦૨૬ પર કોલ કરીને સ્લોટ બુક કરી શકાય છે.",
    support: "કિસાન કોલ સેન્ટર: ૧૮૦૦-૧૮૦-૧૫૫૧.",
    unrelated: "આ પ્રશ્ન અનાજ ખરીદી સાથે સંબંધિત નથી. કૃપા કરીને માત્ર ખરીદ કેન્દ્ર, સ્લોટ બુકિંગ, લાઇન ટોકન, ટેકાના ભાવ (MSP) અને ચુકવણી અંગેના પ્રશ્નો પૂછો."
  },
  pa: {
    greetings: [
      "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਕਿਸਾਨ ਵੀਰੋ! ਮੈਂ ਫ਼ਸਲ ਖ਼ਰੀਦ ਕ੍ਰਿਸ਼ੀ ਸਹਾਇਕ AI ਹਾਂ।",
      "ਖ਼ਰੀਦ ਕੇਂਦਰ, ਸਲਾਟ ਬੁਕਿੰਗ, ਕਤਾਰ ਟੋਕਨ ਅਤੇ ਐਮਐਸਪੀ ਬਾਰੇ ਪੁੱਛੋ।"
    ],
    slotBooking: "'ਸਲਾਟ ਬੁੱਕ ਕਰੋ' 'ਤੇ ਕਲਿੱਕ ਕਰੋ ਜਾਂ 1800-890-2026 'ਤੇ ਕਾਲ ਕਰੋ।",
    queue: "'ਕਤਾਰ ਸਥਿਤੀ' ਵਿੱਚ ਆਪਣਾ ਲਾਈਵ ਟੋਕਨ ਦੇਖੋ।",
    payment: "ਤੁਲਾਈ ਤੋਂ ਬਾਅਦ ਪੈਸੇ ਸਿੱਧੇ ਤੁਹਾਡੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ DBT ਰਾਹੀਂ ਆਉਂਦੇ ਹਨ।",
    msp: "ਐਮਐਸਪੀ: ਝੋਨਾ: ₹2,300/ਕੁਇੰਟਲ, ਕਣਕ: ₹2,275/ਕੁਇੰਟਲ, ਕਪਾਹ: ₹7,121/ਕੁਇੰਟਲ।",
    centers: "ਕੇਂਦਰ ਸਵੇਰੇ 8:30 ਤੋਂ ਸ਼ਾਮ 5:30 ਤੱਕ ਖੁੱਲ੍ਹੇ ਰਹਿੰਦੇ ਹਨ।",
    documents: "ਜ਼ਰੂਰੀ ਦਸਤਾਵੇਜ਼: ਆਧਾਰ ਕਾਰਡ, ਬੈਂਕ ਪਾਸਬੁੱਕ, ਜਮ੍ਹਾਬੰਦੀ/ਫ਼ਰਦ।",
    ivrPhone: "1800-890-2026 'ਤੇ ਕਾਲ ਕਰਕੇ ਸਲਾਟ ਬੁੱਕ ਕਰ ਸਕਦੇ ਹੋ।",
    support: "ਕਿਸਾਨ ਹੈਲਪਲਾਈਨ: 1800-180-1551।",
    unrelated: "ਇਹ ਸਵਾਲ ਫ਼ਸਲ ਖ਼ਰੀਦ ਨਾਲ ਸੰਬੰਧਿਤ ਨਹੀਂ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਸਿਰਫ਼ ਖ਼ਰੀਦ ਕੇਂਦਰ, ਸਲਾਟ ਬੁਕਿੰਗ, ਕਤਾਰ ਟੋਕਨ, ਐਮਐਸਪੀ ਅਤੇ ਭੁਗਤਾਨ ਬਾਰੇ ਹੀ ਪੁੱਛੋ।"
  },
  or: {
    greetings: [
      "ନମସ୍କାର କୃଷକ ବନ୍ଧୁଗଣ! ମୁଁ ଶସ୍ୟ ସଂଗ୍ରହ କୃଷି ସହାୟକ AI।",
      "କ୍ରୟ କେନ୍ଦ୍ର, ସ୍ଲଟ୍ ବୁକିଂ, ଧାଡ଼ି ଟୋକନ୍ ଏବଂ MSP ବିଷୟରେ ପଚାରନ୍ତୁ।"
    ],
    slotBooking: "'ସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ' ବିଭାଗକୁ ଯାଆନ୍ତୁ କିମ୍ବା ୧୮୦୦-୮୯୦-୨୦୨୬ ରେ କଲ୍ କରନ୍ତୁ।",
    queue: "'ଧାଡ଼ି ସ୍ଥିତି' ରେ ଆପଣଙ୍କ ଟୋକନ୍ ନମ୍ବର ଦେଖନ୍ତୁ।",
    payment: "ଶସ୍ୟ ଯାଞ୍ଚ ପରେ ଟଙ୍କା DBT ମାଧ୍ୟମରେ ସିଧାସଳଖ ବ୍ୟାଙ୍କ ଖାତାକୁ ଆସିବ।",
    msp: "ସହାୟକ ମୂଲ୍ୟ: ଧାନ: ₹୨,୩୦୦/କ୍ୱିଣ୍ଟାଲ, କପା: ₹୭,୧୨୧/କ୍ୱିଣ୍ଟାଲ।",
    centers: "କେନ୍ଦ୍ରଗୁଡ଼ିକ ସକାଳ ୮:୩୦ ରୁ ସନ୍ଧ୍ୟା ୫:୩০ ପର୍ଯ୍ୟନ୍ତ ଖୋଲା ରହିବ।",
    documents: "ଆବଶ୍ୟକୀୟ କାଗଜପତ୍ର: ଆଧାର କାର୍ଡ, ବ୍ୟାଙ୍କ ପାସବୁକ୍, ଜମି ପଟ୍ଟା।",
    ivrPhone: "୧୮୦୦-୮୯୦-୨୦୨୬ ରେ କଲ୍ କରି ସ୍ଲଟ୍ ବୁକ୍ କରିପାରିବେ।",
    support: "କିସାନ କଲ୍ ସେଣ୍ଟର: ୧୮୦୦-୧୮୦-୧୫୫୧।",
    unrelated: "ଏହି ପ୍ରଶ୍ନଟି ଶସ୍ୟ କ୍ରୟ ସହିତ ସମ୍ପର୍କିତ ନୁହେଁ। ଦୟାକରି କେବଳ କ୍ରୟ କେନ୍ଦ୍ର, ସ୍ଲଟ୍ ବୁକିଂ, ଧାଡ଼ି ଟୋକନ୍, MSP ମୂଲ୍ୟ ଏବଂ ଦେୟ ବିଷୟରେ ପଚାରନ୍ତୁ।"
  }
};

/**
 * Smart and precise chatbot reply selector with strict guardrails
 */
export function getChatbotReply(text, lang = 'en') {
  const currentLang = chatbotResponses[lang] ? lang : 'en';
  const responses = chatbotResponses[currentLang];
  const query = (text || '').toLowerCase().trim();

  if (!query) {
    return responses.greetings[0];
  }

  // 1. Greetings
  if (query.match(/^(hi|hello|hey|namaste|namaskar|pranam|vanakkam|nomoshkar|sat sri akal|హాయ్|నమస్తే|నమస్కారం|नमस्ते|வணக்கம்|ನಮಸ್ಕಾರ|ഹലോ|ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ)/i)) {
    return responses.greetings[Math.floor(Math.random() * responses.greetings.length)];
  }

  // 2. Slot Booking / Appointment / Dates
  if (query.match(/(slot|book|booking|reserve|appointment|schedule|date|tomorrow|today|स्लॉट|बुक|స్లాట్|బుకింగ్|తేదీ|ಕಾಯ್ದಿರಿಸಿ|ਸਲਾਟ|সময়|তারিখ|స్లాట్ బుక్)/i)) {
    return responses.slotBooking;
  }

  // 3. Queue / Live Token / Position / Wait time
  if (query.match(/(queue|token|position|wait|waiting|line|कतार|टोकन|క్యూ|టోకెన్|வரிசை|ಸರದಿ|ਕਤਾਰ|সারি|ଧାଡ଼ି|లైవ్ టోకెన్)/i)) {
    return responses.queue;
  }

  // 4. Payment / DBT / Bank Account / Sanction / Money transfer
  if (query.match(/(pay|payment|dbt|pfms|money|bank|amount|rupee|account|sanction|पैसा|भुगतान|బ్యాంక్|డబ్బులు|చెల్లింపు|ఖాతా|பணம்|ವಹಿವಾਟು|পেমেন্ট|টাকা|ଦେୟ|मंजूरी)/i)) {
    return responses.payment;
  }

  // 5. MSP / Price / Rates / Paddy / Wheat / Cotton / Maize / Soyabean / Pulses
  if (query.match(/(msp|price|rate|cost|paddy|wheat|cotton|maize|soyabean|pulse|grain|crop|धान|गेहूं|कपास|मूल्य|రేట్|ధర|మద్దతు|వరి|పత్తి|ಬೆಲೆ|ਕੀਮਤ|দাম|ମୂଲ୍ୟ|క్వింటా)/i)) {
    return responses.msp;
  }

  // 6. Procurement Center Timings / Location / Moisture / Weighing
  if (query.match(/(center|centre|mandi|yard|timing|open|close|time|moisture|weigh|quality|grade|मंडी|केंद्र|సమయం|తేమ|కేంద్రం|மையம்|ಕೇಂದ್ರ|ਸਮਾਂ)/i)) {
    return responses.centers;
  }

  // 7. Documents Required / Aadhaar / Pattadar Passbook
  if (query.match(/(document|paper|aadhaar|aadhar|passbook|land|record|pattadar|दस्तावेज|कागजात|పత్రాలు|ఆధార్|ಪಾಸ್‌ಬುಕ್|ದಾಖಲೆ|নথি)/i)) {
    return responses.documents;
  }

  // 8. Offline / Non-smartphone / IVR Telephone / Call booking
  if (query.match(/(phone|telephone|call|dial|toll free|offline|ivr|smartphone|no phone|कॉल|फोन|ఫోన్|కాల్|టోల్‌ఫ్రీ|ಕರೆ|কল)/i)) {
    return responses.ivrPhone;
  }

  // 9. Helpline / Grievance / Complaint / Contact
  if (query.match(/(help|helpline|support|contact|complaint|grievance|officer|number|मदद|हेल्पलाइन|సహాయం|నెంబర్|உதவி|ಸಹಾಯ|ਮਦਦ|সাহায্য)/i)) {
    return responses.support;
  }

  // ==========================================================
  // STRICT GUARDRAIL: If query is out of scope / unrelated
  // ==========================================================
  return responses.unrelated;
}
