export const languagesList = [
  { code: 'en', name: 'English', nativeName: 'English', speechCode: 'en-IN', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', speechCode: 'hi-IN', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', speechCode: 'te-IN', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', speechCode: 'ta-IN', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', speechCode: 'kn-IN', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', speechCode: 'ml-IN', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', speechCode: 'mr-IN', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', speechCode: 'bn-IN', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', speechCode: 'gu-IN', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', speechCode: 'pa-IN', flag: '🇮🇳' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', speechCode: 'or-IN', flag: '🇮🇳' }
];

export const translations = {
  en: {
    title: "🌾 Farmer Procurement Hub",
    tagline: "Transparent, Seamless Grain Procurement & Real-time Queue Tracking",
    register: "Register Farmer",
    login: "Login with Mobile",
    sendOtp: "Send OTP",
    sendingOtp: "Sending OTP...",
    verifyOtp: "Verify OTP & Login",
    verifyingOtp: "Verifying...",
    enterOtp: "Enter 6-digit OTP",
    resendOtp: "Resend OTP",
    otpSentTo: "OTP sent to",
    demoOtpBadge: "Demo OTP for Testing:",
    bookSlot: "Book Slot",
    queueStatus: "Queue Status",
    payment: "Payment & MSP",
    logout: "Logout",
    fullName: "Full Name",
    phone: "Mobile Number",
    aadhar: "Aadhar / ID Number",
    address: "Village / District Address",
    bankAccount: "Bank Account Number",
    upi: "UPI ID (Optional)",
    registerBtn: "Register & Get Started",
    welcome: "Welcome back",
    selectSlot: "Select a Procurement Slot",
    queuePosition: "Your Queue Token",
    payNow: "Claim / Confirm Payment",
    help: "Krishi AI Assistant",
    alreadyRegistered: "Already registered? Login with Mobile Number",
    newFarmer: "New farmer? Register here",
    otpVerification: "Mobile OTP Verification",
    enterMobile: "Enter 10-digit Mobile Number",
    phoneRequired: "Please enter a valid 10-digit mobile number",
    fillAllFields: "Please fill all required fields",
    chatbotTitle: "🌾 Krishi Sahayak (Multilingual AI)",
    chatPlaceholder: "Ask about slots, queue, payment, MSP or speak...",
    voiceListening: "Listening... Speak now",
    voiceNotSupported: "Voice recognition is not supported in this browser",
    center: "Procurement Center",
    date: "Date",
    time: "Time Slot",
    capacity: "Capacity",
    status: "Status",
    confirmed: "Confirmed",
    pending: "Pending",
    completed: "Completed",
    totalInQueue: "Total Farmers in Queue",
    estimatedWait: "Estimated Wait Time",
    amount: "Procurement Amount (₹)",
    transactionId: "Transaction ID",
    paid: "Paid to Bank",
    unpaid: "Payment Processing",
    adminPanel: "Admin Panel",
    createSlot: "Create New Procurement Slot",
    allSlots: "All Scheduled Slots",
    noSlots: "No slots available at the moment.",
    noBookings: "No bookings found yet. Book your first slot above!",
    bookedSuccessfully: "Slot booked successfully!",
    loginSuccess: "Logged in successfully!",
    regSuccess: "Registered successfully! Welcome to the hub.",
    liveQueueUpdates: "Live Real-Time Queue Updates Connected"
  },
  hi: {
    title: "🌾 किसान खरीद एवं टोकन हब",
    tagline: "पारदर्शी फसल खरीद और रीयल-टाइम कतार ट्रैकिंग",
    register: "किसान पंजीकरण",
    login: "मोबाइल नंबर से लॉगिन",
    sendOtp: "ओटीपी भेजें",
    sendingOtp: "ओटीपी भेजा जा रहा है...",
    verifyOtp: "ओटीपी सत्यापित करें और लॉगिन करें",
    verifyingOtp: "सत्यापन हो रहा है...",
    enterOtp: "6 अंकों का ओटीपी दर्ज करें",
    resendOtp: "ओटीपी पुनः भेजें",
    otpSentTo: "ओटीपी इस नंबर पर भेजा गया:",
    demoOtpBadge: "परीक्षण हेतु ओटीपी:",
    bookSlot: "स्लॉट बुक करें",
    queueStatus: "कतार स्थिति",
    payment: "भुगतान एवं एमएसपी",
    logout: "लॉगआउट",
    fullName: "पूरा नाम",
    phone: "मोबाइल नंबर",
    aadhar: "आधार / पहचान पत्र नंबर",
    address: "गाँव / जिला का पता",
    bankAccount: "बैंक खाता संख्या",
    upi: "यूपीआई आईडी (वैकल्पिक)",
    registerBtn: "पंजीकरण करें और आगे बढ़ें",
    welcome: "स्वागत है",
    selectSlot: "खरीद स्लॉट चुनें",
    queuePosition: "आपका टोकन नंबर",
    payNow: "भुगतान प्राप्त करें",
    help: "कृषि सहायक (AI)",
    alreadyRegistered: "पहले से पंजीकृत हैं? यहाँ लॉगिन करें",
    newFarmer: "नए किसान? यहाँ पंजीकरण करें",
    otpVerification: "मोबाइल ओटीपी सत्यापन",
    enterMobile: "10 अंकों का मोबाइल नंबर दर्ज करें",
    phoneRequired: "कृपया सही 10 अंकों का मोबाइल नंबर दर्ज करें",
    fillAllFields: "कृपया सभी आवश्यक विवरण भरें",
    chatbotTitle: "🌾 कृषि सहायक (AI वाणी सहायक)",
    chatPlaceholder: "स्लॉट, कतार, भुगतान या एमएसपी के बारे में पूछें...",
    voiceListening: "सुन रहा हूँ... बोलिए",
    voiceNotSupported: "इस ब्राउज़र में ध्वनि पहचान समर्थित नहीं है",
    center: "खरीद केंद्र",
    date: "दिनांक",
    time: "समय स्लॉट",
    capacity: "क्षमता",
    status: "स्थिति",
    confirmed: "स्वीकृत",
    pending: "प्रतीक्षारत",
    completed: "पूर्ण",
    totalInQueue: "कतार में कुल किसान",
    estimatedWait: "अनुमानित प्रतीक्षा समय",
    amount: "खरीद राशि (₹)",
    transactionId: "लेनदेन संख्या",
    paid: "बैंक में स्थानांतरित",
    unpaid: "प्रक्रियाधीन",
    adminPanel: "व्यवस्थापक पैनल",
    createSlot: "नया खरीद स्लॉट जोड़ें",
    allSlots: "उपलब्ध स्लॉट",
    noSlots: "वर्तमान में कोई स्लॉट उपलब्ध नहीं है।",
    noBookings: "अभी तक कोई स्लॉट बुक नहीं किया गया है।",
    bookedSuccessfully: "स्लॉट सफलतापूर्वक बुक हो गया!",
    loginSuccess: "सफलतापूर्वक लॉगिन हो गया!",
    regSuccess: "पंजीकरण सफल! किसान हब में आपका स्वागत है।",
    liveQueueUpdates: "रीयल-टाइम कतार अपडेट चालू है"
  },
  te: {
    title: "🌾 రైతు ధాన్య సేకరణ కేంద్రం",
    tagline: "పారదర్శక ధాన్య కొనుగోళ్లు మరియు ప్రత్యక్ష క్యూ సమాచారం",
    register: "రైతు నమోదు",
    login: "మొబైల్ నంబర్ లాగిన్",
    sendOtp: "OTP పంపండి",
    sendingOtp: "OTP పంపుతోంది...",
    verifyOtp: "OTP ధృవీకరించి లాగిన్ అవ్వండి",
    verifyingOtp: "ధృవీకరిస్తోంది...",
    enterOtp: "6 అంకెల OTP నమోదు చేయండి",
    resendOtp: "OTP మళ్లీ పంపండి",
    otpSentTo: "OTP పంపబడిన నంబర్:",
    demoOtpBadge: "పరీక్ష OTP:",
    bookSlot: "స్లాట్ బుక్ చేయండి",
    queueStatus: "క్యూ స్థితి",
    payment: "చెల్లింపు & మద్దతు ధర",
    logout: "లాగ్ అవుట్",
    fullName: "పూర్తి పేరు",
    phone: "మొబైల్ నంబర్",
    aadhar: "ఆధార్ / ID సంఖ్య",
    address: "గ్రామం / జిల్లా చిరునామా",
    bankAccount: "బ్యాంక్ ఖాతా సంఖ్య",
    upi: "UPI ID (ఐచ్ఛికం)",
    registerBtn: "నమోదు చేసి ప్రారంభించండి",
    welcome: "స్వాగతం",
    selectSlot: "సేకరణ స్లాట్ ఎంచుకోండి",
    queuePosition: "మీ క్యూ టోకెన్",
    payNow: "చెల్లింపు స్వీకరించండి",
    help: "కృషి సహాయక్ (AI)",
    alreadyRegistered: "ఇప్పటికే నమోదు చేసుకున్నారా? ఇక్కడ లాగిన్ అవ్వండి",
    newFarmer: "కొత్త రైతు? ఇక్కడ నమోదు చేసుకోండి",
    otpVerification: "మొబైల్ OTP ధృవీకరణ",
    enterMobile: "10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి",
    phoneRequired: "దయచేసి సరైన 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి",
    fillAllFields: "దయచేసి అవసరమైన అన్ని వివరాలను పూరించండి",
    chatbotTitle: "🌾 కృషి సహాయక్ (AI వాయిస్ అసిస్టెంట్)",
    chatPlaceholder: "స్లాట్, క్యూ, చెల్లింపు లేదా మద్దతు ధర గురించి అడగండి...",
    voiceListening: "వింటున్నాను... మాట్లాడండి",
    voiceNotSupported: "ఈ బ్రౌజర్‌లో వాయిస్ రికగ్నిషన్ అందుబాటులో లేదు",
    center: "సేకరణ కేంద్రం",
    date: "తేదీ",
    time: "సమయం స్లాట్",
    capacity: "సామర్థ్యం",
    status: "స్థితి",
    confirmed: "ధృవీకరించబడింది",
    pending: "పెండింగ్‌లో ఉంది",
    completed: "పూర్తయింది",
    totalInQueue: "క్యూలో ఉన్న రైతుల సంఖ్య",
    estimatedWait: "వేచి ఉండే సమయం",
    amount: "చెల్లింపు మొత్తం (₹)",
    transactionId: "లావాదేవీ ID",
    paid: "బ్యాంకుకు జమ అయింది",
    unpaid: "ప్రక్రియలో ఉంది",
    adminPanel: "అడ్మిన్ ప్యానెల్",
    createSlot: "కొత్త సేకరణ స్లాట్ జోడించండి",
    allSlots: "అందుబాటులో ఉన్న స్లాట్లు",
    noSlots: "ప్రస్తుతం స్లాట్‌లు అందుబాటులో లేవు.",
    noBookings: "ఇంకా ఎటువంటి స్లాట్ బుకింగ్ లేదు.",
    bookedSuccessfully: "స్లాట్ విజయవంతంగా బుక్ చేయబడింది!",
    loginSuccess: "లాగిన్ విజయవంతమైంది!",
    regSuccess: "నమోదు పూర్తయింది! రైతు హబ్‌కు స్వాగతం.",
    liveQueueUpdates: "లైవ్ క్యూ అప్‌డేట్‌లు అందుబాటులో ఉన్నాయి"
  },
  ta: {
    title: "🌾 விவசாயி கொள்முதல் மையம்",
    tagline: "வெளிப்படையான தானிய கொள்முதல் மற்றும் நேரலை வரிசை கண்காணிப்பு",
    register: "விவசாயி பதிவு",
    login: "மொபைல் எண் மூலம் உள்நுழை",
    sendOtp: "OTP அனுப்பு",
    sendingOtp: "OTP அனுப்பப்படுகிறது...",
    verifyOtp: "OTP சரிபார்த்து உள்நுழையவும்",
    verifyingOtp: "சரிபார்க்கப்படுகிறது...",
    enterOtp: "6 இலக்க OTP ஐ உள்ளிடவும்",
    resendOtp: "OTP மீண்டும் அனுப்பு",
    otpSentTo: "OTP அனுப்பப்பட்ட எண்:",
    demoOtpBadge: "சோதனை OTP:",
    bookSlot: "இடத்தை முன்பதிவு செய்",
    queueStatus: "வரிசை நிலை",
    payment: "பணம் & MSP",
    logout: "வெளியேறு",
    fullName: "முழு பெயர்",
    phone: "மொபைல் எண்",
    aadhar: "ஆதார் / அடையாள எண்",
    address: "முகவரி",
    bankAccount: "வங்கி கணக்கு எண்",
    upi: "UPI ஐடி",
    registerBtn: "பதிவு செய்து தொடங்கு",
    welcome: "வரவேற்கிறோம்",
    selectSlot: "கொள்முதல் நேரத்தைத் தேர்ந்தெடு",
    queuePosition: "உங்கள் வரிசை டோக்கன்",
    payNow: "பணம் பெறுங்கள்",
    help: "விவசாய AI உதவியாளர்",
    alreadyRegistered: "ஏற்கனவே பதிவு செய்துள்ளீர்களா? உள்நுழையவும்",
    newFarmer: "புதிய விவசாயியா? பதிவு செய்யுங்கள்",
    otpVerification: "மொபைல் OTP சரிபார்ப்பு",
    enterMobile: "10 இலக்க மொபைல் எண்ணை உள்ளிடவும்",
    phoneRequired: "சரியான மொபைல் எண்ணை உள்ளிடவும்",
    fillAllFields: "அனைத்து விவரங்களையும் நிரப்பவும்",
    chatbotTitle: "🌾 கிருஷி சகாயக் (AI உதவியாளர்)",
    chatPlaceholder: "முன்பதிவு, வரிசை, பணம் பற்றி கேளுங்கள்...",
    voiceListening: "கேட்கிறது... பேசுங்கள்",
    voiceNotSupported: "குரல் அங்கீகாரம் இந்த உலாவியில் ஆதரிக்கப்படவில்லை",
    center: "கொள்முதல் மையம்",
    date: "தேதி",
    time: "நேரம்",
    capacity: "அளவு",
    status: "நிலை",
    confirmed: "உறுதியானது",
    pending: "நிலுவையில்",
    completed: "முடிந்தது",
    totalInQueue: "வரிசையில் உள்ள விவசாயிகள்",
    estimatedWait: "எதிர்பார்க்கப்படும் நேரம்",
    amount: "தொகை (₹)",
    transactionId: "பரிவர்த்தனை எண்",
    paid: "வங்கியில் செலுத்தப்பட்டது",
    unpaid: "செயல்பாட்டில் உள்ளது",
    adminPanel: "நிர்வாக குழு",
    createSlot: "புதிய இடத்தை உருவாக்கு",
    allSlots: "அனைத்து இடங்கள்",
    noSlots: "இடங்கள் எதுவும் இல்லை.",
    noBookings: "முன்பதிவு எதுவும் இல்லை.",
    bookedSuccessfully: "இடம் முன்பதிவு செய்யப்பட்டது!",
    loginSuccess: "உள்நுழைவு வெற்றிகரமானது!",
    regSuccess: "பதிவு வெற்றிகரமானது!",
    liveQueueUpdates: "நேரலை வரிசை இணைப்பு செயலில் உள்ளது"
  },
  kn: {
    title: "🌾 ರೈತ ಧಾನ್ಯ ಖರೀದಿ ಕೇಂದ್ರ",
    tagline: "ಪಾರದರ್ಶಕ ಧಾನ್ಯ ಖರೀದಿ ಮತ್ತು ನೇರ ಸರದಿ ಸಾಲು ಪರಿಶೀಲನೆ",
    register: "ರೈತರ ನೋಂದಣಿ",
    login: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯೊಂದಿಗೆ ಲಾಗಿನ್",
    sendOtp: "OTP ಕಳುಹಿಸಿ",
    sendingOtp: "OTP ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...",
    verifyOtp: "OTP ದೃಢೀಕರಿಸಿ ಲಾಗಿನ್ ಮಾಡಿ",
    verifyingOtp: "ದೃಢೀಕರಿಸಲಾಗುತ್ತಿದೆ...",
    enterOtp: "6 ಅಂಕಿಯ OTP ನಮೂದಿಸಿ",
    resendOtp: "OTP ಮರುಕಳುಹಿಸಿ",
    otpSentTo: "OTP ಕಳುಹಿಸಿದ ಮೊಬೈಲ್:",
    demoOtpBadge: "ಪರೀಕ್ಷಾ OTP:",
    bookSlot: "ಸ್ಲಾಟ್ ಕಾಯ್ದಿರಿಸಿ",
    queueStatus: "ಸರದಿ ಸಾಲಿನ ಸ್ಥಿತಿ",
    payment: "ಪಾವತಿ ಮತ್ತು ಬೆಂಬಲ ಬೆಲೆ",
    logout: "ಲಾಗ್ ಔಟ್",
    fullName: "ಸಂಪೂರ್ಣ ಹೆಸರು",
    phone: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    aadhar: "ಆಧಾರ್ / ಗುರುತಿನ ಸಂಖ್ಯೆ",
    address: "ಗ್ರಾಮ / ವಿಳಾಸ",
    bankAccount: "ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ",
    upi: "UPI ಐಡಿ",
    registerBtn: "ನೋಂದಾಯಿಸಿ ಮುಂದುವರಿಯಿರಿ",
    welcome: "ಸ್ವಾಗತ",
    selectSlot: "ಖರೀದಿ ಸ್ಲಾಟ್ ಆಯ್ಕೆಮಾಡಿ",
    queuePosition: "ನಿಮ್ಮ ಸರದಿ ಟೋಕನ್",
    payNow: "ಪಾವತಿ ಪಡೆಯಿರಿ",
    help: "ಕೃಷಿ ಸಹಾಯಕ (AI)",
    alreadyRegistered: "ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ",
    newFarmer: "ಹೊಸ ರೈತರೇ? ಇಲ್ಲಿ ನೋಂದಾಯಿಸಿ",
    otpVerification: "ಮೊಬೈಲ್ OTP ಪರಿಶೀಲನೆ",
    enterMobile: "10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    phoneRequired: "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ 10 ಅಂಕಿಯ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    fillAllFields: "ದಯವಿಟ್ಟು ಎಲ್ಲಾ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ",
    chatbotTitle: "🌾 ಕೃಷಿ ಸಹಾಯಕ (AI ಧ್ವನಿ ಸಹಾಯಕ)",
    chatPlaceholder: "ಸ್ಲಾಟ್, ಸರದಿ, ಪಾವತಿ ಅಥವಾ MSP ಬಗ್ಗೆ ಕೇಳಿ...",
    voiceListening: "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ... ಮಾತನಾಡಿ",
    voiceNotSupported: "ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆ ಬೆಂಬಲಿತವಾಗಿಲ್ಲ",
    center: "ಖರೀದಿ ಕೇಂದ್ರ",
    date: "ದಿನಾಂಕ",
    time: "ಸಮಯ",
    capacity: "ಸಾಮರ್ಥ್ಯ",
    status: "ಸ್ಥಿತಿ",
    confirmed: "ದೃಢೀಕರಿಸಲಾಗಿದೆ",
    pending: "ಬಾಕಿ ಇದೆ",
    completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    totalInQueue: "ಸರದಿಯಲ್ಲಿರುವ ರೈತರು",
    estimatedWait: "ಅಂದಾಜು ಕಾಯುವ ಸಮಯ",
    amount: "ಮೊತ್ತ (₹)",
    transactionId: "ವಹಿವಾಟು ಐಡಿ",
    paid: "ಬ್ಯಾಂಕ್‌ಗೆ ಪಾವತಿಸಲಾಗಿದೆ",
    unpaid: "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ",
    adminPanel: "ನಿರ್ವಾಹಕ ಫಲಕ",
    createSlot: "ಹೊಸ ಸ್ಲಾಟ್ ರಚಿಸಿ",
    allSlots: "ಲಭ್ಯವಿರುವ ಸ್ಲಾಟ್‌ಗಳು",
    noSlots: "ಯಾವುದೇ ಸ್ಲಾಟ್ ಲಭ್ಯವಿಲ್ಲ.",
    noBookings: "ಇನ್ನೂ ಯಾವುದೇ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಲಾಗಿಲ್ಲ.",
    bookedSuccessfully: "ಸ್ಲಾಟ್ ಯಶಸ್ವಿಯಾಗಿ ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ!",
    loginSuccess: "ಲಾಗಿನ್ ಯಶಸ್ವಿಯಾಗಿದೆ!",
    regSuccess: "ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ!",
    liveQueueUpdates: "ಲೈವ್ ಸರದಿ ಸಾಲು ನವೀಕರಣ ಸಕ್ರಿಯವಾಗಿದೆ"
  },
  ml: {
    title: "🌾 കർഷക സംഭരണ കേന്ദ്രം",
    tagline: "സുതാര്യമായ ധാന്യ സംഭരണവും തത്സമയ ക്യൂ വിവരങ്ങളും",
    register: "കർഷക രജിസ്ട്രേഷൻ",
    login: "മൊബൈൽ ലോഗിൻ",
    sendOtp: "OTP അയക്കുക",
    sendingOtp: "OTP അയക്കുന്നു...",
    verifyOtp: "OTP സ്ഥിരീകരിച്ച് ലോഗിൻ ചെയ്യുക",
    verifyingOtp: "സ്ഥിരീകരിക്കുന്നു...",
    enterOtp: "6 അക്ക OTP നൽകുക",
    resendOtp: "OTP വീണ്ടും അയക്കുക",
    otpSentTo: "OTP അയച്ച നമ്പർ:",
    demoOtpBadge: "ടെസ്റ്റ് OTP:",
    bookSlot: "സ്ലാറ്റ് ബുക്ക് ചെയ്യുക",
    queueStatus: "ക്യൂ നില",
    payment: "പേയ്‌മെന്റും താങ്ങുവിലയും",
    logout: "ലോഗ് ഔട്ട്",
    fullName: "പൂർണ്ണ പേര്",
    phone: "മൊബൈൽ നമ്പർ",
    aadhar: "ആധാർ നമ്പർ",
    address: "വിലാസം",
    bankAccount: "ബാങ്ക് അക്കൗണ്ട് നമ്പർ",
    upi: "UPI ഐഡി",
    registerBtn: "രജിസ്റ്റർ ചെയ്ത് തുടങ്ങുക",
    welcome: "സ്വാഗതം",
    selectSlot: "സ്ലാറ്റ് തിരഞ്ഞെടുക്കുക",
    queuePosition: "നിങ്ങളുടെ ക്യൂ ടോക്കൺ",
    payNow: "പേയ്‌മെന്റ് സ്വീകരിക്കുക",
    help: "കൃഷി സഹായക് (AI)",
    alreadyRegistered: "മുമ്പ് രജിസ്റ്റർ ചെയ്തതാണോ? ലോഗിൻ ചെയ്യുക",
    newFarmer: "പുതിയ കർഷകനാണോ? ഇവിടെ രജിസ്റ്റർ ചെയ്യുക",
    otpVerification: "മൊബൈൽ OTP സ്ഥിരീകരണം",
    enterMobile: "10 അക്ക മൊബൈൽ നമ്പർ നൽകുക",
    phoneRequired: "ശരിയായ മൊബൈൽ നമ്പർ നൽകുക",
    fillAllFields: "എല്ലാ വിവരങ്ങളും പൂരിപ്പിക്കുക",
    chatbotTitle: "🌾 കൃഷി സഹായക് (AI വോയ്‌സ് അസിസ്റ്റന്റ്)",
    chatPlaceholder: "സ്ലാറ്റ്, ക്യൂ, പേയ്‌മെന്റ് എന്നിവയെക്കുറിച്ച് ചോദിക്കുക...",
    voiceListening: "കേൾക്കുന്നു... സംസാരിക്കൂ",
    voiceNotSupported: "വോയ്‌സ് റെക്കഗ്നിഷൻ ലഭ്യമല്ല",
    center: "സംഭരണ കേന്ദ്രം",
    date: "തീയതി",
    time: "സമയം",
    capacity: "ശേഷി",
    status: "നില",
    confirmed: "സ്ഥിരീകരിച്ചു",
    pending: "തീർപ്പുകൽപ്പിക്കാത്തത്",
    completed: "പൂർത്തിയായി",
    totalInQueue: "ക്യൂവിലുള്ള കർഷകർ",
    estimatedWait: "പ്രതീക്ഷിക്കുന്ന സമയം",
    amount: "തുക (₹)",
    transactionId: "ഇടപാട് നമ്പർ",
    paid: "ബാങ്കിലേക്ക് നൽകി",
    unpaid: "നടപടിക്രമത്തിലാണ്",
    adminPanel: "അഡ്മിൻ പാനൽ",
    createSlot: "പുതിയ സ്ലാറ്റ് ചേർക്കുക",
    allSlots: "ലഭ്യമായ സ്ലാറ്റുകൾ",
    noSlots: "സ്ലാറ്റുകൾ ലഭ്യമല്ല.",
    noBookings: "ബുക്കിംഗുകൾ ഒന്നും ലഭ്യമല്ല.",
    bookedSuccessfully: "സ്ലാറ്റ് ബുക്ക് ചെയ്തു!",
    loginSuccess: "ലോഗിൻ വിജയകരം!",
    regSuccess: "രജിസ്ട്രേഷൻ വിജയകരം!",
    liveQueueUpdates: "ലൈവ് ക്യൂ അപ്‌ഡേറ്റുകൾ സജീവമാണ്"
  },
  mr: {
    title: "🌾 शेतकरी धान्य खरेदी केंद्र",
    tagline: "पारदर्शक पीक खरेदी आणि थेट रांग ट्रॅकिंग",
    register: "शेतकरी नोंदणी",
    login: "मोबाईल नंबरने लॉगिन",
    sendOtp: "OTP पाठवा",
    sendingOtp: "OTP पाठवला जात आहे...",
    verifyOtp: "OTP सत्यापित करा आणि लॉगिन करा",
    verifyingOtp: "तपासत आहे...",
    enterOtp: "६ अंकी OTP टाका",
    resendOtp: "OTP पुन्हा पाठवा",
    otpSentTo: "OTP पाठवला:",
    demoOtpBadge: "चाचणी OTP:",
    bookSlot: "स्लॉट बुक करा",
    queueStatus: "रांग स्थिती",
    payment: "पेमेंट आणि हमीभाव",
    logout: "लॉगआउट",
    fullName: "पूर्ण नाव",
    phone: "मोबाईल नंबर",
    aadhar: "आधार क्रमांक",
    address: "पत्ता",
    bankAccount: "बँक खाते क्रमांक",
    upi: "UPI आयडी",
    registerBtn: "नोंदणी करा आणि पुढे जा",
    welcome: "स्वागत आहे",
    selectSlot: "खरेदी स्लॉट निवडा",
    queuePosition: "तुमचा टोकन नंबर",
    payNow: "पेमेंट प्राप्त करा",
    help: "कृषी सहाय्यक (AI)",
    alreadyRegistered: "आधीच नोंदणीकृत आहात? लॉगिन करा",
    newFarmer: "नवीन शेतकरी? नोंदणी करा",
    otpVerification: "मोबाईल OTP पडताळणी",
    enterMobile: "१० अंकी मोबाईल नंबर टाका",
    phoneRequired: "कृपया वैध मोबाईल नंबर टाका",
    fillAllFields: "कृपया सर्व माहिती भरा",
    chatbotTitle: "🌾 कृषी सहाय्यक (AI व्हॉईस असिस्टंट)",
    chatPlaceholder: "स्लॉट, रांग, हमीभाव किंवा पेमेंटबद्दल विचारा...",
    voiceListening: "ऐकत आहे... बोला",
    voiceNotSupported: "या ब्राउझरमध्ये व्हॉईस सपोर्ट नाही",
    center: "खरेदी केंद्र",
    date: "तारीख",
    time: "वेळ",
    capacity: "क्षमता",
    status: "स्थिती",
    confirmed: "मंजूर",
    pending: "प्रलंबित",
    completed: "पूर्ण",
    totalInQueue: "रांगेतील शेतकरी संख्या",
    estimatedWait: "अंदाजे वेळ",
    amount: "रक्कम (₹)",
    transactionId: "व्यवहार आयडी",
    paid: "बँकेत जमा झाले",
    unpaid: "प्रक्रिया सुरू आहे",
    adminPanel: "प्रशासक पॅनेल",
    createSlot: "नवीन स्लॉट जोडा",
    allSlots: "सर्व स्लॉट",
    noSlots: "कोणतेही स्लॉट उपलब्ध नाहीत.",
    noBookings: "अद्याप कोणतीही बुकिंग नाही.",
    bookedSuccessfully: "स्लॉट यशस्वीरित्या बुक झाला!",
    loginSuccess: "लॉगिन यशस्वी!",
    regSuccess: "नोंदणी यशस्वी!",
    liveQueueUpdates: "थेट रांग अपडेट्स सुरू आहेत"
  },
  bn: {
    title: "🌾 কৃষক শস্য ক্রয় কেন্দ্র",
    tagline: "স্বচ্ছ শস্য সংগ্রহ এবং রিয়েল-টাইম সারি ট্র্যাকিং",
    register: "কৃষক নিবন্ধন",
    login: "মোবাইল নম্বর দিয়ে লগইন",
    sendOtp: "OTP পাঠান",
    sendingOtp: "OTP পাঠানো হচ্ছে...",
    verifyOtp: "OTP যাচাই করে লগইন করুন",
    verifyingOtp: "যাচাই করা হচ্ছে...",
    enterOtp: "৬ সংখ্যার OTP লিখুন",
    resendOtp: "OTP পুনরায় পাঠান",
    otpSentTo: "OTP পাঠানো হয়েছে:",
    demoOtpBadge: "পরীক্ষার OTP:",
    bookSlot: "স্লট বুক করুন",
    queueStatus: "সারির অবস্থা",
    payment: "পেমেন্ট ও সহায়ক মূল্য",
    logout: "লগআউট",
    fullName: "সম্পূর্ণ নাম",
    phone: "মোবাইল নম্বর",
    aadhar: "আধার নম্বর",
    address: "ঠিকানা",
    bankAccount: "ব্যাঙ্ক অ্যাকাউন্ট নম্বর",
    upi: "UPI আইডি",
    registerBtn: "নিবন্ধন সম্পন্ন করুন",
    welcome: "স্বাগতম",
    selectSlot: "ক্রয় স্লট বেছে নিন",
    queuePosition: "আপনার টোকেন নম্বর",
    payNow: "পেমেন্ট গ্রহণ করুন",
    help: "কৃষি সহায়ক (AI)",
    alreadyRegistered: "ইতিমধ্যে নিবন্ধিত? লগইন করুন",
    newFarmer: "নতুন কৃষক? নিবন্ধন করুন",
    otpVerification: "মোবাইল OTP যাচাইকরণ",
    enterMobile: "১০ সংখ্যার মোবাইল নম্বর দিন",
    phoneRequired: "সঠিক মোবাইল নম্বর লিখুন",
    fillAllFields: "সমস্ত তথ্য পূরণ করুন",
    chatbotTitle: "🌾 কৃষি সহায়ক (AI ভয়েস সহকারী)",
    chatPlaceholder: "স্লট, সারি, পেমেন্ট বা মূল্য সম্পর্কে জিজ্ঞাসা করুন...",
    voiceListening: "শুনছি... কথা বলুন",
    voiceNotSupported: "ভয়েস স্বীকৃতি সমর্থিত নয়",
    center: "সংগ্রহ কেন্দ্র",
    date: "তারিখ",
    time: "সময়",
    capacity: "ধারণক্ষমতা",
    status: "অবস্থা",
    confirmed: "অনুমোদিত",
    pending: "অপেক্ষমান",
    completed: "সম্পন্ন",
    totalInQueue: "সারিতে মোট কৃষক",
    estimatedWait: "আনুমানিক অপেক্ষার সময়",
    amount: "পরিমাণ (₹)",
    transactionId: "লেনদেন আইডি",
    paid: "ব্যাঙ্কে জমা হয়েছে",
    unpaid: "প্রক্রিয়াধীন",
    adminPanel: "অ্যাডমিন প্যানেল",
    createSlot: "নতুন স্লট তৈরি করুন",
    allSlots: "উপলব্ধ স্লটসমূহ",
    noSlots: "কোনো স্লট উপলব্ধ নেই।",
    noBookings: "কোনো বুকিং পাওয়া যায়নি।",
    bookedSuccessfully: "স্লট সফলভাবে বুক হয়েছে!",
    loginSuccess: "লগইন সফল হয়েছে!",
    regSuccess: "নিবন্ধন সফল হয়েছে!",
    liveQueueUpdates: "লাইভ সারি আপডেট সংযুক্ত"
  },
  gu: {
    title: "🌾 ખેડૂત ખરીદ કેન્દ્ર",
    tagline: "પારદર્શક અનાજ ખરીદી અને લાઈવ લાઇન ટ્રેકિંગ",
    register: "ખેડૂત નોંધણી",
    login: "મોબાઇલ નંબરથી લોગિન",
    sendOtp: "OTP મોકલો",
    sendingOtp: "OTP મોકલાઈ રહ્યો છે...",
    verifyOtp: "OTP ચકાસીને લોગિન કરો",
    verifyingOtp: "ચકાસણી ચાલુ છે...",
    enterOtp: "૬ અંકનો OTP દાખલ કરો",
    resendOtp: "OTP ફરી મોકલો",
    otpSentTo: "OTP મોકલેલ નંબર:",
    demoOtpBadge: "ટેસ્ટિંગ OTP:",
    bookSlot: "સ્લોટ બુક કરો",
    queueStatus: "લાઇન સ્થિતિ",
    payment: "ચુકવણી અને ટેકાના ભાવ",
    logout: "લૉગ આઉટ",
    fullName: "પૂરું નામ",
    phone: "મોબાઇલ નંબર",
    aadhar: "આધાર નંબર",
    address: "સરનામું",
    bankAccount: "બેંક ખાતા નંબર",
    upi: "UPI આઈડી",
    registerBtn: "નોંધણી કરો અને આગળ વધો",
    welcome: "સ્વાગત છે",
    selectSlot: "ખરીદ સ્લોટ પસંદ કરો",
    queuePosition: "તમારો ટોકન નંબર",
    payNow: "ચુકવણી મેળવો",
    help: "કૃષિ સહાયક (AI)",
    alreadyRegistered: "પહેલેથી નોંધાયેલા છો? લોગિન કરો",
    newFarmer: "નવા ખેડૂત? અહીં નોંધણી કરો",
    otpVerification: "મોબાઇલ OTP ચકાસણી",
    enterMobile: "૧૦ અંકનો મોબાઇલ નંબર નાખો",
    phoneRequired: "સાચો મોબાઇલ નંબર દાખલ કરો",
    fillAllFields: "કૃપા કરીને બધી વિગતો ભરો",
    chatbotTitle: "🌾 કૃષિ સહાયક (AI વોઇસ સહાયક)",
    chatPlaceholder: "સ્લોટ, લાઇન, ચુકવણી અથવા ટેકાના ભાવ વિશે પૂછો...",
    voiceListening: "સાંભળી રહ્યું છે... બોલો",
    voiceNotSupported: "વોઇસ સપોર્ટ ઉપલબ્ધ નથી",
    center: "ખરીદ કેન્દ્ર",
    date: "તારીખ",
    time: "સમય",
    capacity: "ક્ષમતા",
    status: "સ્થિતિ",
    confirmed: "મંજૂર",
    pending: "બાકી",
    completed: "પૂર્ણ",
    totalInQueue: "લાઇનમાં કુલ ખેડૂતો",
    estimatedWait: "અંદાજિત રાહ જોવાનો સમય",
    amount: "રકમ (₹)",
    transactionId: "ટ્રાન્ઝેક્શન આઈડી",
    paid: "બેંકમાં જમા થઈ ગયું",
    unpaid: "પ્રક્રિયામાં છે",
    adminPanel: "એડમિન પેનલ",
    createSlot: "નવો સ્લોટ ઉમેરો",
    allSlots: "બધા સ્લોટ્સ",
    noSlots: "કોઈ સ્લોટ ઉપલબ્ધ નથી.",
    noBookings: "હજુ સુધી કોઈ બુકિંગ નથી.",
    bookedSuccessfully: "સ્લોટ સફળતાપૂર્વક બુક થયો!",
    loginSuccess: "લોગિન સફળ થયું!",
    regSuccess: "નોંધણી સફળ થઈ!",
    liveQueueUpdates: "લાઈવ લાઈન અપડેટ્સ ચાલુ છે"
  },
  pa: {
    title: "🌾 ਕਿਸਾਨ ਖ਼ਰੀਦ ਕੇਂਦਰ",
    tagline: "ਪਾਰਦਰਸ਼ੀ ਫ਼ਸਲ ਖ਼ਰੀਦ ਅਤੇ ਲਾਈਵ ਕਤਾਰ ਟਰੈਕਿੰਗ",
    register: "ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    login: "ਮੋਬਾਈਲ ਨੰਬਰ ਨਾਲ ਲੌਗਇਨ",
    sendOtp: "OTP ਭੇਜੋ",
    sendingOtp: "OTP ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
    verifyOtp: "OTP ਤਸਦੀਕ ਕਰੋ ਤੇ ਲੌਗਇਨ ਕਰੋ",
    verifyingOtp: "ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ...",
    enterOtp: "6 ਅੰਕਾਂ ਦਾ OTP ਦਰਜ ਕਰੋ",
    resendOtp: "OTP ਦੁਬਾਰਾ ਭੇਜੋ",
    otpSentTo: "OTP ਇਸ ਨੰਬਰ 'ਤੇ ਭੇਜਿਆ ਗਿਆ:",
    demoOtpBadge: "ਟੈਸਟਿੰਗ OTP:",
    bookSlot: "ਸਲਾਟ ਬੁੱਕ ਕਰੋ",
    queueStatus: "ਕਤਾਰ ਸਥਿਤੀ",
    payment: "ਭੁਗਤਾਨ ਅਤੇ ਐਮਐਸਪੀ",
    logout: "ਲੌਗ ਆਉਟ",
    fullName: "ਪੂਰਾ ਨਾਮ",
    phone: "ਮੋਬਾਈਲ ਨੰਬਰ",
    aadhar: "ਆਧਾਰ ਨੰਬਰ",
    address: "ਪਤਾ",
    bankAccount: "ਬੈਂਕ ਖਾਤਾ ਨੰਬਰ",
    upi: "UPI ਆਈਡੀ",
    registerBtn: "ਰਜਿਸਟਰ ਕਰੋ ਅਤੇ ਸ਼ੁਰੂ ਕਰੋ",
    welcome: "ਜੀ ਆਇਆਂ ਨੂੰ",
    selectSlot: "ਖ਼ਰੀਦ ਸਲਾਟ ਚੁਣੋ",
    queuePosition: "ਤੁਹਾਡਾ ਟੋਕਨ ਨੰਬਰ",
    payNow: "ਭੁਗਤਾਨ ਪ੍ਰਾਪਤ ਕਰੋ",
    help: "ਕ੍ਰਿਸ਼ੀ ਸਹਾਇਕ (AI)",
    alreadyRegistered: "ਪਹਿਲਾਂ ਤੋਂ ਰਜਿਸਟਰਡ ਹੋ? ਲੌਗਇਨ ਕਰੋ",
    newFarmer: "ਨਵੇਂ ਕਿਸਾਨ? ਇੱਥੇ ਰਜਿਸਟਰ ਕਰੋ",
    otpVerification: "ਮੋਬਾਈਲ OTP ਪੁਸ਼ਟੀ",
    enterMobile: "10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ",
    phoneRequired: "ਕਿਰਪਾ ਕਰਕੇ ਸਹੀ ਮੋਬਾਈਲ ਨੰਬਰ ਭਰੋ",
    fillAllFields: "ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੀ ਜਾਣਕਾਰੀ ਭਰੋ",
    chatbotTitle: "🌾 ਕ੍ਰਿਸ਼ੀ ਸਹਾਇਕ (AI ਵੌਇਸ ਅਸਿਸਟੈਂਟ)",
    chatPlaceholder: "ਸਲਾਟ, ਕਤਾਰ, ਭੁਗਤਾਨ ਜਾਂ ਐਮਐਸਪੀ ਬਾਰੇ ਪੁੱਛੋ...",
    voiceListening: "ਸੁਣ ਰਿਹਾ ਹੈ... ਬੋਲੋ",
    voiceNotSupported: "ਵੌਇਸ ਪਛਾਣ ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਉਪਲਬਧ ਨਹੀਂ ਹੈ",
    center: "ਖ਼ਰੀਦ ਕੇਂਦਰ",
    date: "ਮਿਤੀ",
    time: "ਸਮਾਂ",
    capacity: "ਸਮਰੱਥਾ",
    status: "ਸਥਿਤੀ",
    confirmed: "ਪੁਸ਼ਟੀ ਹੋਈ",
    pending: "ਬਕਾਇਆ",
    completed: "ਮੁਕੰਮਲ",
    totalInQueue: "ਕਤਾਰ ਵਿੱਚ ਕੁੱਲ ਕਿਸਾਨ",
    estimatedWait: "ਅੰਦਾਜ਼ਨ ਉਡੀਕ ਸਮਾਂ",
    amount: "ਰਕਮ (₹)",
    transactionId: "ਲੈਣ-ਦੇਣ ਨੰਬਰ",
    paid: "ਬੈਂਕ ਵਿੱਚ ਜਮ੍ਹਾ ਹੋ ਗਿਆ",
    unpaid: "ਕਾਰਵਾਈ ਚੱਲ ਰਹੀ ਹੈ",
    adminPanel: "ਐਡਮਿਨ ਪੈਨਲ",
    createSlot: "ਨਵਾਂ ਸਲਾਟ ਬਣਾਓ",
    allSlots: "ਸਾਰੇ ਉਪਲਬਧ ਸਲਾਟ",
    noSlots: "ਕੋਈ ਸਲਾਟ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।",
    noBookings: "ਕੋਈ ਬੁਕਿੰਗ ਨਹੀਂ ਮਿਲੀ।",
    bookedSuccessfully: "ਸਲਾਟ ਸਫਲਤਾਪੂਰਵਕ ਬੁੱਕ ਹੋ ਗਿਆ!",
    loginSuccess: "ਲੌਗਇਨ ਸਫਲ ਰਿਹਾ!",
    regSuccess: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸਫਲ ਰਹੀ!",
    liveQueueUpdates: "ਲਾਈਵ ਕਤਾਰ ਅੱਪਡੇਟ ਚਾਲੂ ਹੈ"
  },
  or: {
    title: "🌾 କୃଷକ ଶସ୍ୟ ସଂଗ୍ରହ କେନ୍ଦ୍ର",
    tagline: "ସ୍ୱଚ୍ଛ ଶସ୍ୟ କ୍ରୟ ଏବଂ ଲାଇଭ୍ ଧାଡ଼ି ଟ୍ରାକିଂ",
    register: "କୃଷକ ପଞ୍ଜୀକରଣ",
    login: "ମୋବାଇଲ୍ ନମ୍ବର ଲଗଇନ୍",
    sendOtp: "OTP ପଠାନ୍ତୁ",
    sendingOtp: "OTP ପଠାଯାଉଛି...",
    verifyOtp: "OTP ଯାଞ୍ଚ କରି ଲଗଇନ୍ କରନ୍ତୁ",
    verifyingOtp: "ଯାଞ୍ଚ ହେଉଛି...",
    enterOtp: "୬ ଅଙ୍କ ବିଶିଷ୍ଟ OTP ଦିଅନ୍ତୁ",
    resendOtp: "OTP ପୁନଃ ପଠାନ୍ତୁ",
    otpSentTo: "OTP ପଠାଯାଇଥିବା ନମ୍ବର:",
    demoOtpBadge: "ପରୀକ୍ଷା OTP:",
    bookSlot: "ସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ",
    queueStatus: "ଧାଡ଼ି ସ୍ଥିତି",
    payment: "ଦେୟ ଏବଂ ସହାୟକ ମୂଲ୍ୟ",
    logout: "ଲଗ୍ ଆଉଟ୍",
    fullName: "ସମ୍ପୂର୍ଣ୍ଣ ନାମ",
    phone: "ମୋବାଇଲ୍ ନମ୍ବର",
    aadhar: "ଆଧାର ନମ୍ବର",
    address: "ଠିକଣା",
    bankAccount: "ବ୍ୟାଙ୍କ ଖାତା ନମ୍ବର",
    upi: "UPI ଆଇଡି",
    registerBtn: "ପଞ୍ଜୀକରଣ କରି ଆଗକୁ ବଢ଼ନ୍ତୁ",
    welcome: "ସ୍ୱାଗତ",
    selectSlot: "ସଂଗ୍ରହ ସ୍ଲଟ୍ ଚୟନ କରନ୍ତୁ",
    queuePosition: "ଆପଣଙ୍କ ଟୋକନ୍ ନମ୍ବର",
    payNow: "ଦେୟ ଗ୍ରହଣ କରନ୍ତୁ",
    help: "କୃଷି ସହାୟକ (AI)",
    alreadyRegistered: "ପୂର୍ବରୁ ପଞ୍ଜୀକୃତ କି? ଲଗଇନ୍ କରନ୍ତୁ",
    newFarmer: "ନୂତନ କୃଷକ? ଏଠାରେ ପଞ୍ଜୀକରଣ କରନ୍ତୁ",
    otpVerification: "ମୋବାଇଲ୍ OTP ଯାଞ୍ଚ",
    enterMobile: "୧୦ ଅଙ୍କ ବିଶିଷ୍ଟ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ",
    phoneRequired: "ଦୟାକରି ସଠିକ୍ ମୋବାଇਲ୍ ନମ୍ବਰ ଦିଅନ୍ତୁ",
    fillAllFields: "ଦୟାକରି ସମସ୍ତ ବିବରଣୀ ପୂରଣ କରନ୍ତୁ",
    chatbotTitle: "🌾 କୃଷି ସହାୟକ (AI ଭଏସ୍ ସହାୟକ)",
    chatPlaceholder: "ସ୍ଲଟ୍, ଧାଡ଼ି, ଦେୟ କିମ୍ବା ମୂଲ୍ୟ ବିଷୟରେ ପଚାରନ୍ତୁ...",
    voiceListening: "ଶୁଣୁଛି... କୁହନ୍ତୁ",
    voiceNotSupported: "ଏହି ବ୍ରାଉଜରରେ ଭଏସ୍ ସମର୍ଥିତ ନୁହେଁ",
    center: "ସଂଗ୍ରହ କେନ୍ଦ୍ର",
    date: "ତାରିଖ",
    time: "ସମୟ",
    capacity: "କ୍ଷମତା",
    status: "ସ୍ଥିତି",
    confirmed: "ନିଶ୍ଚିତ",
    pending: "ବକେୟା",
    completed: "ସମ୍ପୂର୍ଣ୍ଣ",
    totalInQueue: "ଧାଡ଼ିରେ ଥିବା କୃଷକ",
    estimatedWait: "ଆନୁମାନିକ ସମୟ",
    amount: "ରାଶି (₹)",
    transactionId: "କାରବାର ଆଇଡି",
    paid: "ବ୍ୟାଙ୍କରେ ଜମା ହୋଇଛି",
    unpaid: "ପ୍ରକ୍ରିୟା ଚାଲିଛି",
    adminPanel: "ପ୍ରଶାସନିକ ପ୍ୟାନେଲ୍",
    createSlot: "ନୂତନ ସ୍ଲଟ୍ ଯୋଡନ୍ତୁ",
    allSlots: "ସମସ୍ତ ସ୍ଲଟ୍",
    noSlots: "କୌଣସି ସ୍ଲଟ୍ ଉପଲବ୍ଧ ନାହିଁ।",
    noBookings: "କୌଣସି ବୁକିଂ ମିଳିନାହିଁ।",
    bookedSuccessfully: "ସ୍ଲଟ୍ ସଫଳତାର ସହ ବୁକ୍ ହେଲା!",
    loginSuccess: "ଲଗଇନ୍ ସଫଳ ହେଲା!",
    regSuccess: "ପଞ୍ଜୀକରଣ ସଫଳ ହେଲା!",
    liveQueueUpdates: "ଲାଇଭ୍ ଧାଡ଼ି ଅଦ୍ୟତନ ସକ୍ରିୟ ଅଛି"
  }
};

export const chatbotResponses = {
  en: {
    greetings: [
      "Hello Farmer Brother/Sister! I am Krishi Sahayak, your AI Assistant. How can I help you today?",
      "Namaste! I can assist you with slot booking, live queue tokens, MSP rates, and direct DBT payments."
    ],
    slotBooking: "To book a procurement slot, go to the 'Book Slot' tab, choose your preferred mandi center, date, and timing, then click 'Reserve Slot'.",
    queue: "You can track your live queue position and token number in real time under the 'Queue Status' section.",
    payment: "All procurement payments are transferred directly via DBT to your linked bank account or UPI ID once grain inspection is complete.",
    registration: "New farmers can register with Name, 10-digit Phone, and Bank details. Once registered, you simply log in with your Mobile Number and OTP!",
    msp: "Current Government MSP Rates: Paddy (Common): ₹2,300/quintal, Wheat: ₹2,275/quintal, Cotton: ₹7,121/quintal, Maize: ₹2,090/quintal.",
    support: "Helpline: Dial 1800-180-1551 (Kisan Call Center) for 24/7 agricultural support. Procurement Mandi opens 8 AM - 6 PM."
  },
  hi: {
    greetings: [
      "नमस्ते किसान भाई/बहन! मैं कृषि सहायक हूँ। मैं आपकी क्या सहायता कर सकता हूँ?",
      "प्रणाम! मैं स्लॉट बुकिंग, कतार टोकन, एमएसपी मूल्य और डीबीटी भुगतान में आपकी मदद कर सकता हूँ।"
    ],
    slotBooking: "स्लॉट बुक करने के लिए 'स्लॉट बुक करें' टैब पर जाएँ, अपनी पसंदीदा मंडी, दिनांक और समय चुनें और 'स्लॉट आरक्षित करें' पर क्लिक करें।",
    queue: "आप 'कतार स्थिति' सेक्शन में अपना लाइव टोकन नंबर और कतार में अपनी स्थिति सीधे देख सकते हैं।",
    payment: "अनाज तुलाई और गुणवत्ता जांच के बाद आपकी फसल की राशि सीधे आपके बैंक खाते या यूपीआई में डीबीटी द्वारा भेज दी जाती है।",
    registration: "नए किसान अपना नाम, 10 अंकों का मोबाइल नंबर और बैंक विवरण भरकर पंजीकरण कर सकते हैं। एक बार पंजीकरण के बाद आप केवल मोबाइल नंबर व ओटीपी से लॉगिन कर सकते हैं।",
    msp: "वर्तमान न्यूनतम समर्थन मूल्य (MSP): धान (सामान्य): ₹2,300/क्विंटल, गेहूँ: ₹2,275/क्विंटल, कपास: ₹7,121/क्विंटल, मक्का: ₹2,090/क्विंटल।",
    support: "किसान कॉल सेंटर हेल्पलाइन: 1800-180-1551 (टोल फ्री)। खरीद केंद्र सुबह 8 बजे से शाम 6 बजे तक खुले रहते हैं।"
  },
  te: {
    greetings: [
      "నమస్కారం రైతు సోదరులారా! నేను కృషి సహాయక్ AI అసిస్టెంట్. నేను మీకు ఎలా సహాయపడగలను?",
      "నమస్తే! స్లాట్ బుకింగ్, లైవ్ క్యూ టోకెన్, మద్దతు ధరలు మరియు బ్యాంక్ చెల్లింపుల సమాచారం నేను అందిస్తాను."
    ],
    slotBooking: "ధాన్య సేకరణ స్లాట్ బుక్ చేయడానికి 'స్లాట్ బుక్ చేయండి' పై క్లిక్ చేసి, మీ కేంద్రం, తేదీ మరియు సమయాన్ని ఎంచుకోండి.",
    queue: "మీ ప్రస్తుత టోకెన్ నంబర్ మరియు క్యూలో మీ స్థానాన్ని 'క్యూ స్థితి' విభాగంలో లైవ్‌గా చూడవచ్చు.",
    payment: "ధాన్యం తూకం పూర్తయిన వెంటనే మీ రిజిస్టర్డ్ బ్యాంక్ ఖాతా లేదా UPI కి DBT ద్వారా నిధులు నేరుగా జమ చేయబడతాయి.",
    registration: "కొత్త రైతులు పేరు, 10 అంకెల మొబైల్ నంబర్ మరియు బ్యాంక్ వివరాలతో నమోదు చేసుకోవచ్చు. ఒకసారి నమోదు చేసుకున్న తర్వాత మొబైల్ OTP ద్వారా నేరుగా లాగిన్ అవ్వవచ్చు.",
    msp: "ప్రస్తుత మద్దతు ధరలు (MSP): వరి (సాధారణం): ₹2,300/క్వింటాల్, గోధుమ: ₹2,275/క్వింటాల్, పత్తి: ₹7,121/క్వింటాల్, మొక్కజొన్న: ₹2,090/క్వింటాల్.",
    support: "రైతు హెల్ప్‌లైన్: 1800-180-1551 (కిసాన్ కాల్ సెంటర్). కొనుగోలు కేంద్రాలు ఉదయం 8 నుండి సాయంత్రం 6 వరకు పనిచేస్తాయి."
  },
  ta: {
    greetings: [
      "வணக்கம் விவசாய தோழரே! நான் கிருஷி சகாயக் AI உதவியாளர். உங்களுக்கு நான் எவ்வாறு உதவ முடியும்?",
      "வணக்கம்! முன்பதிவு, வரிசை டோக்கன், குறைந்தபட்ச ஆதரவு விலை (MSP) மற்றும் வங்கி பரிவர்த்தனை தகவல்களை அறியலாம்."
    ],
    slotBooking: "நேரத்தை முன்பதிவு செய்ய 'இடத்தை முன்பதிவு செய்' என்பதை கிளிக் செய்து, கொள்முதல் மையம் மற்றும் நேரத்தைத் தேர்ந்தெடுக்கவும்.",
    queue: "உங்கள் டோக்கன் எண் மற்றும் வரிசை நிலையை 'வரிசை நிலை' பகுதியில் நேரலையாகக் காணலாம்.",
    payment: "தானிய எடையிடல் முடிந்ததும் தொகை நேரடியாக உங்கள் வங்கிக் கணக்கில் DBT மூலம் வரவு வைக்கப்படும்.",
    registration: "புதிய விவசாயிகள் பெயர் மற்றும் மொபைல் எண் மூலம் பதிவு செய்யலாம். பின் மொபைல் OTP மூலம் எளிதாக உள்நுழையலாம்.",
    msp: "அரசு MSP விலை: நெல்: ₹2,300/குவிண்டால், கோதுமை: ₹2,275/குவிண்டால், பருத்தி: ₹7,121/குவிண்டால், மக்காச்சோளம்: ₹2,090/குவிண்டால்.",
    support: "உதவி எண்: 1800-180-1551 (விவசாயி அழைப்பு மையம்). கொள்முதல் மையங்கள் காலை 8 முதல் மாலை 6 வரை இயங்கும்."
  },
  kn: {
    greetings: [
      "ನಮಸ್ಕಾರ ರೈತ ಬಾಂಧವರೇ! ನಾನು ಕೃಷಿ ಸಹಾಯಕ AI. ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?",
      "ನಮಸ್ಕಾರ! ಸ್ಲಾಟ್ ಬುಕಿಂಗ್, ಸರದಿ ಟೋಕನ್, ಬೆಂಬಲ ಬೆಲೆ (MSP) ಮತ್ತು ಬ್ಯಾಂಕ್ ಜಮೆ ಬಗ್ಗೆ ಮಾಹಿತಿ ಪಡೆಯಿರಿ."
    ],
    slotBooking: "ಸ್ಲಾಟ್ ಕಾಯ್ದಿರಿಸಲು 'ಸ್ಲಾಟ್ ಕಾಯ್ದಿರಿಸಿ' ಮೆನುಗೆ ಹೋಗಿ ಕೇಂದ್ರ, ದಿನಾಂಕ ಮತ್ತು ಸಮಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    queue: "ನಿಮ್ಮ ಟೋಕನ್ ಸಂಖ್ಯೆ ಮತ್ತು ಸರದಿ ಸಾಲಿನ ವಿವರಗಳನ್ನು 'ಸರದಿ ಸಾಲಿನ ಸ್ಥಿತಿ'ಯಲ್ಲಿ ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಿ.",
    payment: "ಧಾನ್ಯ ಪರಿಶೀಲನೆ ನಂತರ ನಿಮ್ಮ ಹಣ ನೇರವಾಗಿ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ DBT ಮೂಲಕ ಜಮೆಯಾಗುತ್ತದೆ.",
    registration: "ಹೊಸ ರೈತರು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯೊಂದಿಗೆ ನೋಂದಾಯಿಸಿಕೊಳ್ಳಬಹುದು. ನಂತರ ಮೊಬೈಲ್ OTP ಮೂಲಕ ನೇರವಾಗಿ ಲಾಗಿನ್ ಆಗಬಹುದು.",
    msp: "ಸರ್ಕಾರದ ಬೆಂಬಲ ಬೆಲೆ: ಭತ್ತ: ₹2,300/ಕ್ವಿಂಟಾಲ್, ಗೋಧಿ: ₹2,275/ಕ್ವಿಂಟಾಲ್, ಹತ್ತಿ: ₹7,121/ಕ್ವಿಂಟಾಲ್, ಮೆಕ್ಕೆಜೋಳ: ₹2,090/ಕ್ವಿಂಟಾಲ್.",
    support: "ರೈತ ಸಹಾಯವಾಣಿ: 1800-180-1551. ಕೇಂದ್ರಗಳು ಬೆಳಿಗ್ಗೆ 8 ರಿಂದ ಸಂಜೆ 6 ರವರೆಗೆ ತೆರೆದಿರುತ್ತವೆ."
  },
  ml: {
    greetings: [
      "നമസ്കാരം കർഷക സുഹൃത്തേ! ഞാൻ കൃഷി സഹായക് AI അസിസ്റ്റന്റ്. ഞാൻ എന്ത് സഹായമാണ് ചെയ്യേണ്ടത്?",
      "നമസ്കാരം! സ്ലാറ്റ് ബുക്കിംഗ്, ക്യൂ ടോക്കൺ, താങ്ങുവില (MSP), പേയ്‌മെന്റ് എന്നിവയിൽ ഞാൻ സഹായിക്കാം."
    ],
    slotBooking: "ധാന്യ സംഭരണ സ്ലാറ്റ് ബുക്ക് ചെയ്യാൻ 'സ്ലാറ്റ് ബുക്ക് ചെയ്യുക' ടാബിൽ പോയി തീയതിയും സമയവും തിരഞ്ഞെടുക്കുക.",
    queue: "'ക്യൂ നില' ടാബിൽ നിങ്ങളുടെ ലൈവ് ടോക്കൺ നമ്പറും നിലവിലെ ക്യൂ സ്ഥിതിയും പരിശോധിക്കാം.",
    payment: "ധാന്യം സംഭരിച്ച ശേഷം തുക നിങ്ങളുടെ ബാങ്ക് അക്കൗണ്ടിലേക്ക് DBT വഴി നേരിട്ട് ലഭ്യമാകും.",
    registration: "പുതിയ കർഷകർക്ക് മൊബൈൽ നമ്പർ ഉപയോഗിച്ച് രജിസ്റ്റർ ചെയ്യാം. തുടർന്ന് മൊബൈൽ OTP ഉപയോഗിച്ച് ലോഗിన్ ചെയ്യാം.",
    msp: "സർക്കാർ താങ്ങുവില: നെല്ല്: ₹2,300/ക്വിന്റൽ, ഗോതമ്പ്: ₹2,275/ക്വിന്റൽ, പരുത്തി: ₹7,121/ക്വിന്റൽ.",
    support: "കിസാൻ കോൾ സെന്റർ: 1800-180-1551 (ടോൾ ഫ്രീ)."
  },
  mr: {
    greetings: [
      "नमस्कार शेतकरी बांधवांनो! मी कृषी सहाय्यक AI आहे. मी तुम्हाला कशी मदत करू शकतो?",
      "प्रणाम! स्लॉट बुकिंग, थेट रांग टोकन, हमीभाव आणि डीबीटी पेमेंट माहितीसाठी मी सदैव तत्पर आहे."
    ],
    slotBooking: "स्लॉट बुक करण्यासाठी 'स्लॉट बुक करा' पर्यायावर जा आणि केंद्र, तारीख व वेळ निवडून आरक्षित करा.",
    queue: "तुमचा टोकन क्रमांक आणि थेट रांग 'रांग स्थिती' विभागात तपासू शकता.",
    payment: "धान्य मोजणीनंतर रक्कम थेट तुमच्या बँक खात्यात डीबीटीद्वारे जमा केली जाते.",
    registration: "नवीन शेतकरी मोबाईल नंबर व बँकेच्या तपशीलासह नोंदणी करू शकतात आणि नंतर OTP द्वारे थेट लॉगिन करू शकतात.",
    msp: "हमीभाव (MSP): धान/भात: ₹२,३००/क्विंटल, गहू: ₹२,२७५/क्विंटल, कापूस: ₹७,१२१/क्विंटल, मका: ₹२,०९०/क्विंटल.",
    support: "किसान कॉल सेंटर हेल्पलाईन: १८००-१८०-१५५१ (टोल फ्री)."
  },
  bn: {
    greetings: [
      "নমস্কার কৃষক ভাই ও বোনেরা! আমি কৃষি সহায়ক AI। আমি কীভাবে আপনাকে সাহায্য করতে পারি?",
      "প্রণাম! স্লট বুকিং, লাইভ কিউ টোকেন, সহায়ক মূল্য (MSP) ও ব্যাঙ্ক পেমেন্ট তথ্য জানতে পারেন।"
    ],
    slotBooking: "স্লট বুক করতে 'স্লট বুক করুন' ট্যাবে গিয়ে সংগ্রহের কেন্দ্র, তারিখ ও সময় নির্বাচন করুন।",
    queue: "'সারির অবস্থা' অংশে আপনার বর্তমান টোকেন নম্বর এবং লাইভ কিউ ট্র্যাক করতে পারবেন।",
    payment: "শস্য পরীক্ষার পর সম্পূর্ণ অর্থ সরাসরি আপনার লিঙ্ক করা ব্যাঙ্ক অ্যাকাউন্টে DBT মারফত পৌঁছে যাবে।",
    registration: "নতুন কৃষকরা মোবাইল নম্বর ও ব্যাঙ্ক তথ্য দিয়ে নিবন্ধন করতে পারেন এবং পরে মোবাইল OTP দিয়ে লগইন করতে পারেন।",
    msp: "সরকারি সহায়ক মূল্য (MSP): ধান: ₹২,৩০০/কুইন্টাল, গম: ₹২,২৭৫/কুইন্টাল, তুলা: ₹৭,১২১/কুইন্টাল, ভুট্টা: ₹২,০৯০/কুইন্টাল।",
    support: "কৃষক হেল্পলাইন: ১৮০০-১৮০-১৫৫১ (টোল ফ্রি)। কেন্দ্রগুলি সকাল ৮টা থেকে সন্ধ্যা ৬টা পর্যন্ত খোলা থাকে।"
  },
  gu: {
    greetings: [
      "નમસ્તે ખેડૂત મિત્રો! હું કૃષિ સહાયક AI છું. હું તમને કેવી રીતે મદદ કરી શકું?",
      "નમસ્તે! સ્લોટ બુકિંગ, લાઈવ લાઇન ટોકન, ટેકાના ભાવ અને બેંક ખાતામાં ચુકવણી માહિતી મેળવો."
    ],
    slotBooking: "સ્લોટ બુક કરવા માટે 'સ્લોટ બુક કરો' મેનુમાં જાઓ અને મનપસંદ કેન્દ્ર, તારીખ અને સમય પસંદ કરો.",
    queue: "તમારો ટોકન નંબર અને લાઈવ લાઇન સ્થિતિ 'લાઇન સ્થિતિ' વિભાગમાં તપાસો.",
    payment: "અનાજ તોલણી પછી રકમ સીધી તમારા બેંક ખાતામાં DBT દ્વારા જમા કરવામાં આવે છે.",
    registration: "નવા ખેડૂતો મોબાઇલ નંબરથી નોંધણી કરી શકે છે અને પછી મોબાઇલ OTP દ્વારા સરળતાથી લોગિન કરી શકે છે.",
    msp: "ટેકાના ભાવ (MSP): ડાંગર: ₹૨,૩૦૦/ક્વિન્ટલ, ઘઉં: ₹૨,૨૭૫/ક્વિન્ટલ, કપાસ: ₹૭,૧૨૧/ક્વિન્ટલ.",
    support: "કિસાન કોલ સેન્ટર: ૧૮૦૦-૧૮૦-૧૫૫૧ (ટોલ ફ્રી)."
  },
  pa: {
    greetings: [
      "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਕਿਸਾਨ ਵੀਰੋ ਅਤੇ ਭੈਣੋ! ਮੈਂ ਕ੍ਰਿਸ਼ੀ ਸਹਾਇਕ AI ਹਾਂ। ਮੈਂ ਤੁਹਾਡੀ ਕੀ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?",
      "ਜੀ ਆਇਆਂ ਨੂੰ! ਸਲਾਟ ਬੁਕਿੰਗ, ਲਾਈਵ ਟੋਕਨ, ਐਮਐਸਪੀ ਅਤੇ ਡੀਬੀਟੀ ਭੁਗਤਾਨ ਦੀ ਜਾਣਕਾਰੀ ਲਈ ਪੁੱਛੋ।"
    ],
    slotBooking: "ਸਲਾਟ ਬੁੱਕ ਕਰਨ ਲਈ 'ਸਲਾਟ ਬੁੱਕ ਕਰੋ' 'ਤੇ ਕਲਿੱਕ ਕਰੋ ਅਤੇ ਆਪਣੀ ਪਸੰਦ ਦੀ ਮੰਡੀ ਅਤੇ ਸਮਾਂ ਚੁਣੋ।",
    queue: "ਤੁਸੀਂ 'ਕਤਾਰ ਸਥਿਤੀ' ਸੈਕਸ਼ਨ ਵਿੱਚ ਆਪਣਾ ਲਾਈਵ ਟੋਕਨ ਨੰਬਰ ਅਤੇ ਕਤਾਰ ਦੇਖ ਸਕਦੇ ਹੋ।",
    payment: "ਫ਼ਸਲ ਤੁਲਾਈ ਤੋਂ ਬਾਅਦ ਪੈਸੇ ਸਿੱਧੇ ਤੁਹਾਡੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ DBT ਰਾਹੀਂ ਆ ਜਾਂਦੇ ਹਨ।",
    registration: "ਨਵੇਂ ਕਿਸਾਨ ਮੋਬਾਈਲ ਨੰਬਰ ਨਾਲ ਰਜਿਸਟਰ ਕਰ ਸਕਦੇ ਹਨ ਅਤੇ ਬਾਅਦ ਵਿੱਚ ਮੋਬਾਈਲ OTP ਨਾਲ ਸਿੱਧਾ ਲੌਗਇਨ ਕਰ ਸਕਦੇ ਹਨ।",
    msp: "ਸਰਕਾਰੀ ਐਮਐਸਪੀ ਦਰਾਂ: ਝੋਨਾ: ₹2,300/ਕੁਇੰਟਲ, ਕਣਕ: ₹2,275/ਕੁਇੰਟਲ, ਕਪਾਹ: ₹7,121/ਕੁਇੰਟਲ, ਮੱਕੀ: ₹2,090/ਕੁਇੰਟਲ।",
    support: "ਕਿਸਾਨ ਹੈਲਪਲਾਈਨ: 1800-180-1551 (ਟੋਲ ਫ੍ਰੀ)।"
  },
  or: {
    greetings: [
      "ନମସ୍କାର କୃଷକ ଭାଇ ଓ ଭଉଣୀମାନେ! ମୁଁ କୃଷି ସହାୟକ AI। ମୁଁ ଆପଣଙ୍କୁ କିପରି ସାହାଯ୍ୟ କରିପାରିବି?",
      "ନମସ୍କାର! ସ୍ଲଟ୍ ବୁକିଂ, ଲାଇଭ୍ ଟୋକନ୍, ସହାୟକ ମୂଲ୍ୟ (MSP) ଏବଂ ବ୍ୟାଙ୍କ ଦେୟ ସମ୍ପର୍କରେ ପଚାରନ୍ତୁ।"
    ],
    slotBooking: "ସ୍ଲଟ୍ ବୁକ୍ କରିବାକୁ 'ସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ' ଉପରେ କ୍ଲିକ୍ କରି ମଣ୍ଡି ଏବଂ ସମୟ ଚୟନ କରନ୍ତୁ।",
    queue: "ଆପଣ 'ଧାଡ଼ି ସ୍ଥିତି' ବିଭାଗରେ ଆପଣଙ୍କର ଲାଇଭ୍ ଟୋକନ୍ ନମ୍ବର ଦେଖିପାରିବେ।",
    payment: "ଶସ୍ୟ ଯାଞ୍ଚ ପରେ ସମ୍ପୂର୍ଣ୍ଣ ଟଙ୍କା ସିଧାସଳଖ ଆପଣଙ୍କ ବ୍ୟାଙ୍କ ଖାତାକୁ DBT ମାଧ୍ୟମରେ ପଠାଯାଏ।",
    registration: "ନୂତନ କୃଷକମାନେ ମୋବାଇਲ୍ ନମ୍ବର ଦ୍ୱାରା ପଞ୍ଜୀକରଣ କରିପାରିବେ ଏବଂ ପରେ OTP ଦ୍ୱାରା ସହଜରେ ଲଗଇନ୍ କରିପାରିବେ।",
    msp: "ସରକାରୀ ସହାୟକ ମୂଲ୍ୟ: ଧାନ: ₹୨,୩୦୦/କ୍ୱିଣ୍ଟାଲ, ଗହମ: ₹୨,୨୭୫/କ୍ୱିଣ୍ଟାଲ, କପା: ₹୭,୧୨୧/କ୍ୱିଣ୍ଟାଲ।",
    support: "କିସାନ କଲ୍ ସେଣ୍ଟର: ୧୮୦୦-୧୮୦-୧୫୫୧ (ଟୋଲ୍ ଫ୍ରି)।"
  }
};

export function getChatbotReply(text, lang = 'en') {
  const currentLang = chatbotResponses[lang] ? lang : 'en';
  const responses = chatbotResponses[currentLang];
  const query = (text || '').toLowerCase().trim();

  // 1. Greetings
  if (query.match(/^(hi|hello|hey|namaste|namaskar|pranam|vanakkam|nomoshkar|sat sri akal|హాయ్|నమస్తే|नमस्ते|வணக்கம்|ನಮಸ್ಕಾರ)/i)) {
    return responses.greetings[Math.floor(Math.random() * responses.greetings.length)];
  }

  // 2. Slot Booking / Mandi Timing
  if (query.match(/(slot|book|reserve|timing|date|mandi|center|स्लॉट|बुक|సమయం|తేదీ|స్లాట్|பதிவு|நேரம்|ಕಾಯ್ದಿರಿಸಿ|ਸਲਾਟ|সময়)/i)) {
    return responses.slotBooking;
  }

  // 3. Queue / Token / Live Status
  if (query.match(/(queue|token|position|wait|line|status|कतार|टोकन|క్యూ|టోకెన్|வரிசை|ಸರದಿ|ਕਤਾਰ|সারি|ଧାଡ଼ି)/i)) {
    return responses.queue;
  }

  // 4. Payment / DBT / Bank Account
  if (query.match(/(pay|payment|money|bank|dbt|account|upi|rupee|पैसा|भुगतान|బ్యాంక్|డబ్బులు|చెల్లింపు|பணம்|ವಹಿವಾਟು|পেমেন্ট|টাকা|ଦେୟ)/i)) {
    return responses.payment;
  }

  // 5. MSP / Price / Rates / Paddy / Wheat / Cotton
  if (query.match(/(msp|price|rate|cost|paddy|wheat|cotton|grain|crop|धान|गेहूं|मूल्य|ధర|మద్దతు|பயிர்|ಬೆಲೆ|ਕੀਮਤ|দাম|ମୂଲ୍ୟ)/i)) {
    return responses.msp;
  }

  // 6. Registration / Login / OTP / Aadhar
  if (query.match(/(register|signup|login|otp|aadhar|mobile|phone|नंबर|पंजीकरण|నమోదు|లాగిన్|பதிவு|ನೋಂದಣಿ|ਰਜਿਸਟਰ|নিবন্ধন|ପଞ୍ଜୀକରଣ)/i)) {
    return responses.registration;
  }

  // 7. Helpline / Support / Contact
  if (query.match(/(help|support|contact|helpline|call|phone|मदद|సహాయం|உதவி|ಸಹಾಯ|ਮਦਦ|সাহায্য|ସହାୟତା)/i)) {
    return responses.support;
  }

  // Fallback helpful response
  return responses.greetings[0] + " " + responses.slotBooking;
}

